# 7/10

In [1]:
import numpy as np
import pandas as pd

## Series

### Series 생성

In [2]:
# Series
s = pd.Series([1, 2, 3])
print(s)

0    1
1    2
2    3
dtype: int64


In [3]:
s = pd.Series((1.0, 2.0, 3.0))
print(s)

0    1.0
1    2.0
2    3.0
dtype: float64


In [4]:
s2 = pd.Series(['a', 'b', 'c'])
print(s2)

0    a
1    b
2    c
dtype: object


In [5]:
s_1 = pd.Series(['a', 1, 3.0]) # 문자가 섞여 형변환
print(s_1)

0      a
1      1
2    3.0
dtype: object


### 범위를 이용한 Series 생성

In [6]:
# 범위를 이용한 Series 생성
s = pd.Series(range(10, 14))
print(s)

0    10
1    11
2    12
3    13
dtype: int64


In [7]:
print(np.arange(200))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


In [9]:
s3 = pd.Series(np.arange(200))
print(s3)

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32


In [10]:
# 결측값을 포함한 Series
s = pd.Series([1, 2, 3, np.nan, 6, 8])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64


### index 생성

In [11]:
# 인덱스 명시
s = pd.Series([10, 20, 30], index=[1, 2, 3])
print(s)

1    10
2    20
3    30
dtype: int64


In [12]:
# 문자 인덱스도 가능
s = pd.Series([95, 100, 88], index=['홍길동', '이몽룡', '성춘향'])
print(s)

홍길동     95
이몽룡    100
성춘향     88
dtype: int64


In [13]:
s0 = pd.Series([10, 20, 30], index=[1, 2, 3])
print(s0)

1    10
2    20
3    30
dtype: int64


In [14]:
print(s0.index)

Index([1, 2, 3], dtype='int64')


In [15]:
s00 = pd.Series([1, 2, 3])
print(s00.index)

RangeIndex(start=0, stop=3, step=1)


In [16]:
s = pd.Series([9904312, 3448737, 289045, 2466052], index=['서울', '부산', '인천', '대구'])
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='object')


In [18]:
s.index.name = '광역시' # 인덱스명 지정
print(s)
print(s.index)

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64
Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


In [19]:
print(s.values) # Series의 값 접근

[9904312 3448737  289045 2466052]


In [20]:
s.name = '인구' # Series 이름 지정
print(s)

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


In [21]:
print(s.index)
print(s['인천'], s[2]) # 인덱스 접근, 위치 접근

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')
289045 289045


In [23]:
s03 = pd.Series([1, 2, 3], index=[1, 2, 3])
print(s03)
print(s03[1])
# print(s03[0]) # index를 정수형으로 지정한 경우 위치로 접근할 수 없음

1    1
2    2
3    3
dtype: int64
1


In [24]:
print(s['부산'])

3448737


In [25]:
s[3], s['대구'] # print 함수 없이 두 개의 값을 지정하면 Tuple 형태로 반환

(2466052, 2466052)

In [27]:
print(s, '\n')
# 멀티 인덱스의 경우 리스트 형태로 넣어주어야 한다.
print(s[0], s[3], s[1], '\n')
print(s[[0, 3, 1]])

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64 

9904312 2466052 3448737 

광역시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64


In [29]:
print(s, '\n')
print(s[[1, 2]], s[['부산', '인천']], s[1:3])

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64 

광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64 광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64 광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64


In [30]:
print(s['부산':'대구']) # 문자열 인덱스를 이용해서 슬라이싱이 가능하다.

광역시
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


In [32]:
s_01 = pd.Series([100, 200, 300, 400], index = [1, 2, 3, 4])
print(s_01, '\n')
print(s_01[[2, 3, 4]], '\n')
print(s_01[2:4]) # 슬라이싱 사용, 문자열 인덱스와 다른 방식으로 결과 추출

# 시리즈의 인덱스를 명시할 때 가급적 문자형이 좋음

1    100
2    200
3    300
4    400
dtype: int64 

2    200
3    300
4    400
dtype: int64 

3    300
4    400
dtype: int64


In [33]:
s0 = pd.Series(range(3), index=['a', 'b', 'c'])
print(s0)

a    0
b    1
c    2
dtype: int64


In [35]:
print(s0['a'], s0.a)
print(s['서울'], s.서울)

0 0
9904312 9904312


In [36]:
# 인덱스를 통한 데이터 업데이트
s['서울'] = 10000000
print(s['서울'])

10000000


In [37]:
print(s)

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64


In [38]:
print(s.index)
s1 = pd.Series(np.arange(4), s.index)
print(s1)

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')
광역시
서울    0
부산    1
인천    2
대구    3
dtype: int32


### Series 연산

In [39]:
print(s)

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64


#### 벡터화 연산

In [40]:
pd.Series([1, 2, 3]) + 4

0    5
1    6
2    7
dtype: int64

In [42]:
print(s, '\n')
print(s/1000000)

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64 

광역시
서울    10.000000
부산     3.448737
인천     0.289045
대구     2.466052
Name: 인구, dtype: float64


In [43]:
# 벡터화 인덱싱
s[(s>250e4) & (s<500e4)]

광역시
부산    3448737
Name: 인구, dtype: int64

In [44]:
# Boolean selection
s0 = pd.Series(np.arange(10), np.arange(10)+1)
print(s0)

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32


In [45]:
s0 > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [46]:
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int32

In [47]:
s0[s0%2 == 0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [48]:
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [51]:
# 인덱스에도 가능
print(s0.index > 5, '\n')
print(s0[s0.index > 5])

[False False False False False  True  True  True  True  True] 

6     5
7     6
8     7
9     8
10    9
dtype: int32


In [52]:
# s0의 value가 5를 초과하가 8 미만인 아이템(원소)만 추출하시오
s0[(s0>5) & (s0 < 8)]

7    6
8    7
dtype: int32

In [53]:
(s0>=7).sum() # True의 개수 반환

3

In [54]:
(s0[s0 >= 7]).sum() # 값이 7 이상인 원소들의 합

24

#### 두 시리즈 간의 연산

In [55]:
num_s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c' ,'d'])
num_s2 = pd.Series([5, 6, 7, 8], index=['b', 'c', 'd', 'a'])
print(num_s1, num_s2, sep='\n')

a    1
b    2
c    3
d    4
dtype: int64
b    5
c    6
d    7
a    8
dtype: int64


In [56]:
num_s1 + num_s2 # 같은 index를 찾아 연산

a     9
b     7
c     9
d    11
dtype: int64

In [57]:
num_s3 = pd.Series([5, 6, 7, 8], index=['e', 'b', 'f', 'g'])
num_s4 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [58]:
num_s3 - num_s4 # 동일한 인덱스는 연산, 나머지는 NaN 처리

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [59]:
num_s3.values - num_s4.values # 값만 추출하여 연산 진행 -> 동일 위치 원소끼리 계산

array([4, 4, 4, 4], dtype=int64)

### Dict와 Seires의 관계

In [60]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [61]:
# 인덱스가 서울인 원소가 시리즈에 있는지 확인
'서울' in s

True

In [62]:
# 인덱스가 대전인 원소가 시리즈에 있는지 확인
'대전' in s

False

In [63]:
# 인덱스가 대전인 원소가 시리즈에 없는지 확인
'대전' not in s

True

In [64]:
# dict의 items() 함수 사용 가능
s.items() # zip 객체로 출력

In [65]:
list(s.items())

[('서울', 10000000), ('부산', 3448737), ('인천', 289045), ('대구', 2466052)]

In [66]:
# 시리즈의 각 원소 출력
for k, v in s.items():
    print('%s = %d'% (k, v))

서울 = 10000000
부산 = 3448737
인천 = 289045
대구 = 2466052


In [67]:
# dict를 시리즈로 변환
scores = {'홍길동':96, '이몽룡':100, '성춘향':88}
s = pd.Series(scores)
print(s) # key가 index, value가 value로 변환

홍길동     96
이몽룡    100
성춘향     88
dtype: int64


In [70]:
city = {'서울':9631482, '부산':3393191, '인천':2632035, '대전':1490158}
s = pd.Series(city)
print(s)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [73]:
city = {'서울':9631482, '부산':3393191, '인천':2632035, '대전':1490158}
s = pd.Series(city, index = city.keys())
print(s)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [72]:
s = pd.Series(city, index=['부산', '인천', '서울', '대전']) # 순서가 없음
print(s)

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64


### Series 데이터의 갱신, 추가, 삭제

In [74]:
print(s)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [76]:
# 부산의 인구 값을 1630000으로 변경
s['부산'] = 1630000
print(s)

서울    9631482
부산    1630000
인천    2632035
대전    1490158
dtype: int64


In [77]:
# 원소 삭제 - del 명령
del s['서울']
print(s)

부산    1630000
인천    2632035
대전    1490158
dtype: int64


In [78]:
# 원소 추가
s['대구'] = 1875000
print(s)

부산    1630000
인천    2632035
대전    1490158
대구    1875000
dtype: int64


### 함수

In [80]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])
print(s1)

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64


In [81]:
print(len(s1), s1.size)

16 16


In [82]:
print(s1.shape) # 차원의 형태로 표현하므로 Tuple 형태로 출력된다.

(16,)


In [123]:
print(s1.unique()) # NaN도 하나의 값으로 취급

[ 1.  2.  3.  4.  5.  7. nan]


In [84]:
print(s1.count()) # NaN 값 제외

15


In [85]:
a = np.array([2, 2, 2, 2, np.NaN])
print(a.mean()) # array의 경우 NaN 포함 계산

b = pd.Series(a)
print(b, b.mean(), sep='\n') # NaN이 빠지고 계산

nan
0    2.0
1    2.0
2    2.0
3    2.0
4    NaN
dtype: float64
2.0


In [86]:
print(s1)

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64


In [87]:
print(s1.mean()) # 평균
print(s1.value_counts()) # 빈도수

2.6666666666666665
1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
Name: count, dtype: int64


### 날짜 데이터

In [88]:
# 날짜 인덱스를 이용한 시리즈 생성
index_date = ['2018-10-07', '2018-10-08', '2018-10-09', '2018-10-10']
s4 = pd.Series([200, 195, np.NaN, 205], index = index_date)
print(s4)

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64


In [89]:
type(s4.index[0])

str

In [90]:
pd.date_range(start='2018-10-01', end='2018-10-20') # freq 기본값은 D(day)

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [91]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq='3D')# 3일씩 증가

DatetimeIndex(['2018-10-01', '2018-10-04', '2018-10-07', '2018-10-10',
               '2018-10-13', '2018-10-16', '2018-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [92]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq='w')
# 일주일씩 증가, 한 주의 시작인 일요일을 표시

DatetimeIndex(['2018-10-07', '2018-10-14'], dtype='datetime64[ns]', freq='W-SUN')

In [93]:
pd.date_range(start='2018-10-01', periods=4, freq='w')
# 4개의 날짜 생성

DatetimeIndex(['2018-10-07', '2018-10-14', '2018-10-21', '2018-10-28'], dtype='datetime64[ns]', freq='W-SUN')

In [94]:
pd.date_range(start='2018-10-01', periods=4, freq='m')
# 월의 마지막 날짜 4개 생성

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='M')

In [95]:
pd.date_range(start='2018-10-01', periods=4, freq='M')

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='M')

In [96]:
pd.date_range(start='2018-10-01', periods=4, freq='MS') # 월별 시작일 4개

DatetimeIndex(['2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01'], dtype='datetime64[ns]', freq='MS')

In [97]:
pd.date_range(start='2018-10-01', periods=12, freq='2BM')
# 업무일 기준 2개월 간격 월말

DatetimeIndex(['2018-10-31', '2018-12-31', '2019-02-28', '2019-04-30',
               '2019-06-28', '2019-08-30', '2019-10-31', '2019-12-31',
               '2020-02-28', '2020-04-30', '2020-06-30', '2020-08-31'],
              dtype='datetime64[ns]', freq='2BM')

In [98]:
pd.date_range(start='2018-10-01', periods=4, freq='QS') # 분기 시작일

DatetimeIndex(['2018-10-01', '2019-01-01', '2019-04-01', '2019-07-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [99]:
pd.date_range(start='2018-10-01', periods=4, freq='AS') # 연도 시작일 4개

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [100]:
pd.date_range(start='2018-01-01', periods=4, freq='AS')

DatetimeIndex(['2018-01-01', '2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [101]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='H')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 09:00:00',
               '2018-01-20 10:00:00', '2018-01-20 11:00:00',
               '2018-01-20 12:00:00', '2018-01-20 13:00:00',
               '2018-01-20 14:00:00', '2018-01-20 15:00:00',
               '2018-01-20 16:00:00', '2018-01-20 17:00:00'],
              dtype='datetime64[ns]', freq='H')

In [102]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='BH')
# 업무시간 기준 9 to 5로 설정

DatetimeIndex(['2018-01-22 09:00:00', '2018-01-22 10:00:00',
               '2018-01-22 11:00:00', '2018-01-22 12:00:00',
               '2018-01-22 13:00:00', '2018-01-22 14:00:00',
               '2018-01-22 15:00:00', '2018-01-22 16:00:00',
               '2018-01-23 09:00:00', '2018-01-23 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [103]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='30min')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:30:00',
               '2018-01-20 09:00:00', '2018-01-20 09:30:00',
               '2018-01-20 10:00:00', '2018-01-20 10:30:00',
               '2018-01-20 11:00:00', '2018-01-20 11:30:00',
               '2018-01-20 12:00:00', '2018-01-20 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [105]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='10S')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:00:10',
               '2018-01-20 08:00:20', '2018-01-20 08:00:30',
               '2018-01-20 08:00:40', '2018-01-20 08:00:50',
               '2018-01-20 08:01:00', '2018-01-20 08:01:10',
               '2018-01-20 08:01:20', '2018-01-20 08:01:30'],
              dtype='datetime64[ns]', freq='10S')

## DataFrame

### DataFrame 생성

In [2]:
import pandas as pd
import numpy as np

In [110]:
# 리스트를 이용한 생성
df = pd.DataFrame([['a', 'b', 'c'], ['a', 'a', 'g'], ['a', 'a']])
display(df)

0  1     2
0  a  b     c
1  a  a     g
2  a  a  None

In [109]:
# dict를 이용한 생성
df1 = pd.DataFrame({
    'A':[90, 80, 70],
    'B':[85, 98, 75],
    'C':[88, 99, 77],
    'D':[87, 89, 86]
}, index = [1, 2, 3])
display(df1)

A   B   C   D
1  90  85  88  87
2  80  98  99  89
3  70  75  77  86

In [3]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2000002],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율":[0.0283, 0.0163, 0.0982,0.0141]
}
df3 = pd.DataFrame(data)
display(df3)

2015     2010     2005     2000   지역  2010-2015 증가율
0  9904312  9631482  9762546  9853972  수도권         0.0283
1  3448737  3393191  3512547  3655437  경상권         0.0163
2  2890451  2632035  2517680  2466338  수도권         0.0982
3  2466052  2000002  2456016  2473990  경상권         0.0141

In [7]:
columns = ['지역', '2000', '2005', '2010', '2015', '2010-2015 증가율']
index = ['서울', '부산', '인천', '대구']
df3 = pd.DataFrame(data, index=index, columns=columns)
display(df3)

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [114]:
# Series를 이용한 생성
a = pd.Series([100, 200, 300], ['a', 'b', 'd'])
b = pd.Series([101, 201, 301], ['a', 'b', 'k'])
c = pd.Series([110, 210, 310], ['a', 'b', 'c'])

In [115]:
pd.DataFrame([a, b, c], index=[100, 101, 102]) # 각 Series의 index -> columnname

a      b      d      k      c
100  100.0  200.0  300.0    NaN    NaN
101  101.0  201.0    NaN  301.0    NaN
102  110.0  210.0    NaN    NaN  310.0

In [117]:
# csv 파일을 이용한 생성
train_data = pd.read_csv('./data/train.csv')
train_data.head()

PassengerId  Survived  Pclass   
0            1         0       3  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp   
0                            Braund, Mr. Owen Harris    male  22.0      1  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [14]:
train_data = pd.read_csv('data/train.csv',
                         index_col='PassengerId', # index로 지정할 column 설정
                         usecols=['PassengerId', 'Survived', 'Name', 'Sex', 'Age']) # 실제 사용할 column 설정

In [119]:
train_data.columns

Index(['Survived', 'Name', 'Sex', 'Age'], dtype='object')

In [120]:
train_data.head()

Survived                                               Name   
PassengerId                                                                
1                   0                            Braund, Mr. Owen Harris  \
2                   1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                   1                             Heikkinen, Miss. Laina   
4                   1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                   0                           Allen, Mr. William Henry   

                Sex   Age  
PassengerId                
1              male  22.0  
2            female  38.0  
3            female  26.0  
4            female  35.0  
5              male  35.0

In [122]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Name      891 non-null    object 
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB


# 7/11

## DataFrame(이어서)

### index, column

In [8]:
df3

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [9]:
print(df3.columns, type(df3.columns))

Index(['지역', '2000', '2005', '2010', '2015', '2010-2015 증가율'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [10]:
print(df3.index, type(df3.index))

Index(['서울', '부산', '인천', '대구'], dtype='object') <class 'pandas.core.indexes.base.Index'>


In [11]:
df3.index.name = '도시'
df3.columns.name = '특성'
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [12]:
print(df3.values, type(df3.values))

[['수도권' 9853972 9762546 9631482 9904312 0.0283]
 ['경상권' 3655437 3512547 3393191 3448737 0.0163]
 ['수도권' 2466338 2517680 2632035 2890451 0.0982]
 ['경상권' 2473990 2456016 2000002 2466052 0.0141]] <class 'numpy.ndarray'>


In [13]:
print(df3.values[0], type(df3.values[0]))

['수도권' 9853972 9762546 9631482 9904312 0.0283] <class 'numpy.ndarray'>


In [15]:
# 데이터 파악
train_data.head()

Survived                                               Name   
PassengerId                                                                
1                   0                            Braund, Mr. Owen Harris  \
2                   1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                   1                             Heikkinen, Miss. Laina   
4                   1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                   0                           Allen, Mr. William Henry   

                Sex   Age  
PassengerId                
1              male  22.0  
2            female  38.0  
3            female  26.0  
4            female  35.0  
5              male  35.0

In [16]:
print(len(train_data), train_data.size, train_data.shape) # 행 개수, 값의 개수, 행과 열 개수

891 3564 (891, 4)


In [17]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Name      891 non-null    object 
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 34.8+ KB


In [18]:
train_data.describe()

Survived         Age
count  891.000000  714.000000
mean     0.383838   29.699118
std      0.486592   14.526497
min      0.000000    0.420000
25%      0.000000   20.125000
50%      0.000000   28.000000
75%      1.000000   38.000000
max      1.000000   80.000000

In [19]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [20]:
df3.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2000           9853972  3655437  2466338  2473990
2005           9762546  3512547  2517680  2456016
2010           9631482  3393191  2632035  2000002
2015           9904312  3448737  2890451  2466052
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [21]:
print(df3.T['서울'].values)
print(df3.T['서울']['2000'])

['수도권' 9853972 9762546 9631482 9904312 0.0283]
9853972


### DataFrame의 내용 변경(추가, 삭제, 갱신)

In [22]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

In [24]:
df3.columns

Index(['지역', '2000', '2005', '2010', '2015', '2010-2015 증가율'], dtype='object', name='특성')

In [25]:
df3['2010-2015 증가율'] * 100

도시
서울    2.83
부산    1.63
인천    9.82
대구    1.41
Name: 2010-2015 증가율, dtype: float64

In [26]:
# 열 데이터 갱신
df3['2010-2015 증가율'] = df3['2010-2015 증가율'] * 100

In [27]:
df3['2010-2015 증가율']

도시
서울    2.83
부산    1.63
인천    9.82
대구    1.41
Name: 2010-2015 증가율, dtype: float64

In [28]:
# 열 추가
df3['비고'] = ['특별시', '광역시', '광역시', '광역시']
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율   비고
도시                                                             
서울  수도권  9853972  9762546  9631482  9904312           2.83  특별시
부산  경상권  3655437  3512547  3393191  3448737           1.63  광역시
인천  수도권  2466338  2517680  2632035  2890451           9.82  광역시
대구  경상권  2473990  2456016  2000002  2466052           1.41  광역시

In [29]:
# 열 삭제
del df3['비고']
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [30]:
# 가공열 추가
df3['2005-2015 증가율'] = ((df3['2015'] - df3['2005'])/df3['2005']*100).round(2)
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율  2005-2015 증가율
도시                                                                       
서울  수도권  9853972  9762546  9631482  9904312           2.83           1.45
부산  경상권  3655437  3512547  3393191  3448737           1.63          -1.82
인천  수도권  2466338  2517680  2632035  2890451           9.82          14.81
대구  경상권  2473990  2456016  2000002  2466052           1.41           0.41

In [31]:
# 삭제
del df3['2005-2015 증가율']
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [32]:
# 행 추가
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [33]:
df3.loc['광주'] = ['호남권', 2470000, 2456000, 2453000, 2460000, 1.00]
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

### DataFrame indexing

In [34]:
# columns indexing
print(df3['지역'], type(df3['지역']))

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
광주    호남권
Name: 지역, dtype: object <class 'pandas.core.series.Series'>


In [35]:
df3.지역

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
광주    호남권
Name: 지역, dtype: object

In [37]:
display(df3[['지역']], type(df3[['지역']])) # DataFrame 형태로 반환

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권
광주  호남권

pandas.core.frame.DataFrame

In [38]:
df3[['2010', '2015']]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2000002  2466052
광주  2453000  2460000

In [39]:
# 열이름이 문자열인 경우 수치 인덱스를 사용할 수 없음(위치로 찾기 불가)
try:
    df3[0]
except Exception as e:
    print(type(e))

<class 'KeyError'>


In [40]:
df5 = pd.DataFrame(np.arange(12).reshape(3, 4))
df5

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [41]:
df5[[1, 2]] # 컬럼명이 숫자로 되어있는 경우이다(위치와 상관 없음)

1   2
0  1   2
1  5   6
2  9  10

In [43]:
print(np.arange(12), '\n', np.arange(12).reshape(3, 4)) # 배열의 차원을 변경

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
# row indexing
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

In [46]:
df3[:'서울']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83

In [47]:
df3['인천':'인천']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [48]:
df3[:1]

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83

In [49]:
df3[1:3]

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [50]:
df3['부산':'인천']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [51]:
df3['광주':'광주']

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
광주  호남권  2470000  2456000  2453000  2460000            1.0

In [52]:
# 개별요소 접근
df3['2015']

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
광주    2460000
Name: 2015, dtype: int64

In [53]:
df3['2015']['부산']

3448737

In [ ]:
# df3[['2015']]['부산'] # keyerror 발생(DataFrame을 반환하기 때문)

In [55]:
df3[['2015']]['부산':'부산'] # DataFrame 반환

특성     2015
도시         
부산  3448737

In [56]:
df = df3[['2005', '2010']]
df

특성     2005     2010
도시                  
서울  9762546  9631482
부산  3512547  3393191
인천  2517680  2632035
대구  2456016  2000002
광주  2456000  2453000

In [57]:
# 부산 데이터 추출
df3[['2005', '2010']]['부산':'부산']

특성     2005     2010
도시                  
부산  3512547  3393191

In [58]:
df3.head()

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

In [ ]:
# row indexing에 slicing 사용 -> 불가능
# df3[['2000':'2010']]

In [81]:
# 서울의 2010년 데이터 추출
df3['2015']['서울']
df3.iloc[0, 4]
df3.loc['서울', '2015']

9904312

### drop

In [61]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

In [62]:
# 행 삭제
df3.drop(index=['광주']) # 실제 데이터에 적용 X. 적용하려면 inplace=True 설정

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [63]:
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41
광주  호남권  2470000  2456000  2453000  2460000           1.00

In [64]:
df3.drop(index=['광주', '대구'])

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [65]:
# 원본 수정
df3.drop(index=['광주'], inplace=True)
df3

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2000002  2466052           1.41

In [66]:
# 열 삭제
df3.drop(columns=['2010-2015 증가율', '2010'])

특성   지역     2000     2005     2015
도시                                
서울  수도권  9853972  9762546  9904312
부산  경상권  3655437  3512547  3448737
인천  수도권  2466338  2517680  2890451
대구  경상권  2473990  2456016  2466052

In [68]:
# axis 적용
df3.drop(['대구'], axis=0)

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82

In [69]:
df3.drop(['2010-2015 증가율'], axis=1)

특성   지역     2000     2005     2010     2015
도시                                         
서울  수도권  9853972  9762546  9631482  9904312
부산  경상권  3655437  3512547  3393191  3448737
인천  수도권  2466338  2517680  2632035  2890451
대구  경상권  2473990  2456016  2000002  2466052

In [82]:
# 변수 명이 두 번 이상 출력되어도 모두 콘솔에서 보여주는 방법
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all' # all, last, last_expr, none(default = last_expr)

### loc, iloc

In [83]:
import pandas as pd
import numpy as np

In [84]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=['a', 'b', 'c'],
                  columns=['A', 'B', 'C', 'D'])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [85]:
df.loc['a'] # index 값 하나. Series 반환

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [ ]:
# 열 단독 indexing 불가
# df.loc['A'] # KeyError

In [87]:
# 여러 행 추출
df.loc['b':'c']
df['b':'c']

A   B   C   D
b  14  15  16  17
c  18  19  20  21

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [88]:
# 비연속적인 행 추출 - index값을 list로 사용해 호출
df.loc[['b', 'c']]

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [89]:
# 같은 값 추출에서 결과 타입이 다르게 반환
df.loc['b'] # Series 반환
df.loc[['b']] # DataFrame 반환

A    14
B    15
C    16
D    17
Name: b, dtype: int32

A   B   C   D
b  14  15  16  17

In [90]:
df.loc[['b', 'c']]
df[['B', 'C']] # 열 우선 indexing

A   B   C   D
b  14  15  16  17
c  18  19  20  21

B   C
a  11  12
b  15  16
c  19  20

In [91]:
# Boolean Selection으로 행 선택
df
df.A # Series
df.A > 15 # Boolean Series

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

a    10
b    14
c    18
Name: A, dtype: int32

a    False
b    False
c     True
Name: A, dtype: bool

In [92]:
# 조건식을 index로 사용하면 해당 행을 추출할 수 있다.
df.loc[df.A > 15]

A   B   C   D
c  18  19  20  21

In [93]:
# Boolean Series를 반환하는 함수를 index로 사용
def sel_row(df):
    return df.A > 15

In [94]:
df
sel_row(df)
df.loc[sel_row(df)] # 함수로 return 값을 받아 index로 사용

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

a    False
b    False
c     True
Name: A, dtype: bool

A   B   C   D
c  18  19  20  21

In [95]:
# loc index slicing
df2 = pd.DataFrame(np.arange(10, 26).reshape(4, 4),
                   columns=['a', 'b', 'c', 'd'])
df2

a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [96]:
df2.loc[1:2] # 지정한 끝 행을 포함한다
df2[1:2] # 위치 indexing

a   b   c   d
1  14  15  16  17
2  18  19  20  21

a   b   c   d
1  14  15  16  17

In [97]:
df2
df2.loc[0, 'a'] # 행, 열 모두 받음

a   b   c   d
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

10

In [98]:
# df의 a행 A열 값 출력
df
df.loc['a', 'A']

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

10

In [99]:
# loc index를 이용한 값 변경
df.loc['a', 'A'] = 50
df

A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

In [100]:
df.loc[['a', 'b']]['A'] # Series
df.loc[['a', 'b'], 'A'] # Series
df.loc[['a', 'b'], ['A']] # DataFrame

a    50
b    14
Name: A, dtype: int32

a    50
b    14
Name: A, dtype: int32

A
a  50
b  14

In [101]:
# a 행의 모든 열 추출
df.loc['a']         # Series
df.loc[['a']]       # DataFrame
df.loc['a', :]      # Series
df.loc[['a'], :]    # DataFrame

A    50
B    11
C    12
D    13
Name: a, dtype: int32

A   B   C   D
a  50  11  12  13

A    50
B    11
C    12
D    13
Name: a, dtype: int32

A   B   C   D
a  50  11  12  13

In [102]:
# a행의 B, C열을 추출
df.loc['a']             # Series
df.loc['a', 'B':'C']    # Series
df.loc[['a']]           # DataFrame
df.loc[['a'], 'B':'C']  # DataFrame
df.loc['a', ['B', 'C']] # Series

A    50
B    11
C    12
D    13
Name: a, dtype: int32

B    11
C    12
Name: a, dtype: int32

A   B   C   D
a  50  11  12  13

B   C
a  11  12

B    11
C    12
Name: a, dtype: int32

In [103]:
# B행부터 모든 행의 A열을 추출
df.loc['b':]            # DataFrame
df.loc['b':, 'A']       # Series
df.loc['b':]['A']       # Series
df.loc['b':][['A']]     # DataFrame
df.loc['b':, ['A']]     # DataFrame
df.loc['b':, 'A':'A']   # DataFrame

A   B   C   D
b  14  15  16  17
c  18  19  20  21

b    14
c    18
Name: A, dtype: int32

b    14
c    18
Name: A, dtype: int32

A
b  14
c  18

A
b  14
c  18

A
b  14
c  18

In [104]:
# a, b 행의 B, D열을 DataFrame으로 반환
df.loc['a':'b']
df.loc[['a', 'b']]
df.loc[['a', 'b']][['B', 'D']]
df.loc[['a', 'b'], ['B', 'D']]

A   B   C   D
a  50  11  12  13
b  14  15  16  17

A   B   C   D
a  50  11  12  13
b  14  15  16  17

B   D
a  11  13
b  15  17

B   D
a  11  13
b  15  17

In [105]:
# iloc
df
df.iloc[0, 1]

A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

11

In [106]:
# iloc slicing
df.iloc[0:2, 1:2]

B
a  11
b  15

In [107]:
df.iloc[0:2]
df.iloc[0:2, 1] # Series 반환

A   B   C   D
a  50  11  12  13
b  14  15  16  17

a    11
b    15
Name: B, dtype: int32

In [108]:
df.iloc[2]
df.iloc[2, 1:2]

A    18
B    19
C    20
D    21
Name: c, dtype: int32

B    19
Name: c, dtype: int32

In [109]:
df.iloc[2:3, 1:2] # DataFrame 형태로 추출

B
c  19

In [110]:
df
df.iloc[0:1, -2:]
df.iloc[0, -2:]

A   B   C   D
a  50  11  12  13
b  14  15  16  17
c  18  19  20  21

C   D
a  12  13

C    12
D    13
Name: a, dtype: int32

In [111]:
df.iloc[[0, 1], [1, 2]]

B   C
a  11  12
b  15  16

### value_counts

In [112]:
df = pd.DataFrame({'num_legs':[2, 4, 4, 6],
                   'num_wings':[2, 0, 0, 0]},
                  index=['falcon', 'dog', 'cat', 'ant'])
df

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [113]:
df.num_legs
df.num_legs.value_counts()

falcon    2
dog       4
cat       4
ant       6
Name: num_legs, dtype: int64

num_legs
4    2
2    1
6    1
Name: count, dtype: int64

In [114]:
df.value_counts() # 동일한 값을 갖는 행의 수를 반환

num_legs  num_wings
4         0            2
2         2            1
6         0            1
Name: count, dtype: int64

## Pandas 데이터 처리 및 변환 관련 함수

### 데이터 개수 세기

In [115]:
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [116]:
s.count() # nan은 제외하고 count

9

In [117]:
# random 값으로 DataFrame 생성
np.random.randint(5) # 정수 0~4 사이에서 난수 발생
np.random.randint(5, size = 4) # 난수 4개 생성

1

array([3, 0, 2, 0])

In [118]:
np.random.seed(3) # 난수 값 고정
np.random.randint(5, size = 4)

array([2, 0, 1, 3])

In [119]:
np.random.randint(5, size=4) # seed 리셋

array([0, 0, 0, 3])

In [120]:
# 시드값이 매번 다ㅡㄹ게 전달되도록 코드 작성
import time
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([1, 2, 3, 4])

In [121]:
np.random.seed(3)
df1 = pd.DataFrame(np.random.randint(5, size = (4, 4)))
df1.iloc[2, 3] = np.nan
df1

0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [122]:
# 각 열의 원소 반환
df1.count()

0    4
1    4
2    4
3    3
dtype: int64

### titanic 데이터를 이용한 데이터 처리

In [123]:
titanic = pd.read_csv('./data/test.csv')
del titanic['Unnamed: 0']
titanic.head(10)
titanic.tail(2)

survived  pclass     sex   age  sibsp  parch     fare embarked   class   
0         0       3    male  22.0      1      0   7.2500        S   Third  \
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

survived  pclass   sex   age  sibsp  parch   fare embarked  class  who   
889         1       1  male  26.0      0      0  30.00        C  First  man  \
890         0       3  male  32.0      0      0   7.75        Q  Third  man   

     adult_male deck embark_town alive  alone  
889        True    C   Cherbourg   yes   True  
890        True  NaN  Queenstown    no   True

In [124]:
titanic.to_csv('./data/test.csv')

In [125]:
titanic.count() # 일부 column에 Null값 존재

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

#### 카테고리 값 세기

In [126]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size=100))
len(s2)
s2.value_counts()
s2.value_counts(normalize=True) # 비율

100

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

1    0.22
0    0.18
4    0.17
5    0.16
3    0.14
2    0.13
Name: proportion, dtype: float64

#### 범주형 데이터에 value_counts() 함수 적용

In [127]:
titanic['alive'].dtype
titanic['alive'].value_counts()
titanic['alive'].value_counts(normalize=True)

dtype('O')

alive
no     549
yes    342
Name: count, dtype: int64

alive
no     0.616162
yes    0.383838
Name: proportion, dtype: float64

In [128]:
titanic['alive'].value_counts(normalize=True) * 100

alive
no     61.616162
yes    38.383838
Name: proportion, dtype: float64

In [129]:
# 남녀 비율 확인
titanic['sex'].value_counts()
titanic['sex'].value_counts(normalize=True) * 100

sex
male      577
female    314
Name: count, dtype: int64

sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

#### DataFrame에 value_counts() 함수 사용

In [130]:
titanic[['sex', 'alive']].head(2)

sex alive
0    male    no
1  female   yes

In [131]:
titanic[['sex', 'alive']].value_counts() # 같은 행을 가진 데이터의 개수 파악

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
Name: count, dtype: int64

In [132]:
type(titanic[['sex', 'alive']].value_counts())

pandas.core.series.Series

#### 정렬

In [134]:
s2.value_counts() # 빈도 순으로 내림차순 정렬된다

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [136]:
s2.value_counts().sort_index() # index 기준 정렬
s2.value_counts().sort_index(ascending=False) # index 기준 내림차순 정렬

0    18
1    22
2    13
3    14
4    17
5    16
Name: count, dtype: int64

5    16
4    17
3    14
2    13
1    22
0    18
Name: count, dtype: int64

In [137]:
s2.value_counts().sort_values() # 빈도값을 기준으로 오름차순
s2.value_counts().sort_values(ascending=False) # 빈도값을 기준으로 오름차순

2    13
3    14
5    16
4    17
0    18
1    22
Name: count, dtype: int64

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

In [138]:
# DataFrame 정렬
df1

0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [140]:
# df1.sort_values() # error
df1.sort_values(by=0)
df1.sort_values(by=0, ascending=False)

0  1  2    3
1  0  0  0  3.0
0  2  0  1  3.0
2  2  3  1  NaN
3  2  0  4  4.0

0  1  2    3
0  2  0  1  3.0
2  2  3  1  NaN
3  2  0  4  4.0
1  0  0  0  3.0

In [141]:
df1.sort_values(by=[0, 2], ascending=False) # 여러 행을 지정할 수 있음

0  1  2    3
3  2  0  4  4.0
0  2  0  1  3.0
2  2  3  1  NaN
1  0  0  0  3.0

In [142]:
# 예제 df
df

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [143]:
df.sort_index()
df.sort_index(ascending=False)

num_legs  num_wings
ant            6          0
cat            4          0
dog            4          0
falcon         2          2

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

#### 행/열 합계

In [144]:
# 예제 df 생성
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4, 8)))
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [145]:
# 각 행의 합계
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [147]:
# 각 열의 합계
df2.sum(axis=0)
df2.sum() # axis=0 default

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

In [148]:
# df2['total'] = df2.sum(axis=1)
df2['total'] = df2[[0, 1, 2, 3, 4, 5, 6, 7]].sum(axis=1)
df2

0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

#### mean, min, max

In [149]:
df2

0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

In [150]:
df2.mean(axis=0) # 각 행의 평균
df2.mean(axis=1) # 각 열의 평균

0         6.00
1         8.25
2         6.25
3         6.00
4         3.75
5         2.50
6         1.25
7         4.00
total    38.00
dtype: float64

0    7.777778
1    7.555556
2    9.111111
3    9.333333
dtype: float64

In [151]:
df2.min(axis=0) # 각 행의 최소값
df2.min(axis=1) # 각 열의 최소값

0         4
1         7
2         2
3         4
4         0
5         0
6         0
7         1
total    34
dtype: int64

0    0
1    2
2    0
3    0
dtype: int64

In [152]:
df2.max(axis=0) # 각 행의 최댓값
df2.max(axis=1) # 각 열의 최댓값

0         9
1         9
2         9
3         9
4         9
5         7
6         4
7         7
total    42
dtype: int64

0    35
1    34
2    41
3    42
dtype: int64

In [153]:
# 각 열의 최대값을 구해 max_data 행 추가하기
# df.loc['max_data'] = df2.max(axis=0)
df2.loc['max_data'] = df2[[0, 1, 2, 3, 4, 5, 6, 7]].max(axis=0)
df2

0    1    2    3    4    5    6    7  total
0         5.0  8.0  9.0  5.0  0.0  0.0  1.0  7.0   35.0
1         6.0  9.0  2.0  4.0  5.0  2.0  4.0  2.0   34.0
2         4.0  7.0  7.0  9.0  1.0  7.0  0.0  6.0   41.0
3         9.0  9.0  7.0  6.0  9.0  1.0  0.0  1.0   42.0
max_data  9.0  9.0  9.0  9.0  9.0  7.0  4.0  7.0    NaN