## 6/9(금)

### numpy 작동 확인
- uninstall 방법 `pip uninstall numpy`

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


### 1차원 배열

#### 1. 1차원 배열 생성

In [3]:
# 배열 생성: np.array() 사용

list_value = [10,20,30]  # list, tuple, set , 정수의 기본 dtype은  int32 ( 4byte )
vector1 = np.array(list_value)
print(list_value, type(list_value))
print(vector1, type(vector1), vector1.dtype)

[10, 20, 30] <class 'list'>
[10 20 30] <class 'numpy.ndarray'> int32


In [4]:
list_value = [10.,20.,30.]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [5]:
# upcasting: 자동으로 큰 데이터 타입으로 변경되는 것
list_value = [10.,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [8]:
# 명시적으로 데이터 타입을 변경 가능
list_value = [10.,20.,30.]
vector1 = np.array(list_value, dtype=np.int32)
print(vector1, type(vector1), vector1.dtype)

[10 20 30] <class 'numpy.ndarray'> int32


#### 2. ndarray의 속성

In [10]:
list_value = [10,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

# print(dir(vector1))

# 'T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 
# 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 
# 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 
# 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 
# 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 
# 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 
# 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'

[10 20 30] <class 'numpy.ndarray'> int32


In [63]:
print("1. 벡터의 차원(dimension,axis)갯수:", vector1.ndim)
print("2. 벡터의 각 차원의 크기(shape):", vector1.shape) # tuple로 반환된다.
print("3. 벡터의 총 요소 갯수(size):", vector1.size)
print("4. 벡터의 저장 데이터 type(dtype):", vector1.dtype)

1. 벡터의 차원(dimension,axis)갯수: 1
2. 벡터의 각 차원의 크기(shape): (3,)
3. 벡터의 총 요소 갯수(size): 3
4. 벡터의 저장 데이터 type(dtype): int32


#### 3. 랜덤함수로 벡터 생성

In [16]:
# 1) 랜덤값 고정
np.random.seed(1234)

# 2) np.random.random([갯수])
# 0.0 <= 값 < 1.0 사이의 임의의 float 5개 랜덤값 반환. 갯수 생략하면  1개반환
print("1. random(5)")
arr = np.random.random()
arr = np.random.random(5)
print(arr, type(arr), arr.dtype)

1. random(5)
[0.62210877 0.43772774 0.78535858 0.77997581 0.27259261] <class 'numpy.ndarray'> float64


In [19]:
# 3) np.random.rand([갯수])
# 0 ~ 1의 균등분포에서 표본 추출. 갯수 생략하면  1개반환
print("2. rand(5)")
arr = np.random.rand()
arr = np.random.rand(5)
print(arr, type(arr), arr.dtype)

2. rand(5)
[0.37025075 0.56119619 0.50308317 0.01376845 0.77282662] <class 'numpy.ndarray'> float64


In [22]:
# 3) np.random.randn([갯수])
# 표준편차가 1이고 평균값이 0인 정규분포에서 표본 추출. 갯수 생략하면  1개반환
print("3. randn(5)")
arr = np.random.randn()
arr = np.random.randn(5)
print(arr)

3. randn(5)
[-0.28694235  0.44143825 -0.76987271 -0.97456841  0.70900741]


In [28]:
# 4) np.random.randint(low, high, n)
# 주어진 최소/최대 범위 안에서 임의의 난수 n개 추출
print("4. randint(1,10,3)")
arr = np.random.randint(1,10,3)
print(arr)

4. randint(1,10,3)
[5 3 8]


In [31]:
# 4) np.random.randint(high, size=n)
# 0 ~ 최대(exclusive) 범위안에서 임의의 정수 n개 반환, 복원추출
print("4. randint(5, size=4): ")
arr = np.random.randint(5, size=4)
print(arr)

4. randint(5, size=4): 
[2 1 2 1]


In [34]:
# 5) np.random.choice(리스트)
# 주어진 리스트에서 임의의 값 1개 반환
print("5. np.random.choice(['foo','bar','baz'])")
choice_value = np.random.choice(['foo','bar','baz'])
print(choice_value)

5. np.random.choice(['foo','bar','baz'])
bar


In [35]:
# 6) np.random.shuffle(리스트)
# 주어진 리스트를 shuffle 함.  in-place(True)로 동작됨.
print("6. np.random.shuffle(1,3,56,7,98])")
shuffle_value = [1,3,56,7,98]
np.random.shuffle(shuffle_value)
print(shuffle_value)

6. np.random.shuffle(1,3,56,7,98])
[56, 1, 3, 7, 98]


#### 4. 특정 값으로 벡터를 생성

In [37]:
# 1. np.zeros(shape)
# shape만큼 0으로 채움. 기본 type은 float64
print("1. np.zeros(5):")
data = np.zeros(5)
print(data, data.dtype)
data = np.zeros(5, dtype=np.int32)
print(data, data.dtype)

1. np.zeros(5):
[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [38]:
# 2. np.ones(shape)
# shape만큼  1.0 으로 채움. 기본 type은 float64
print("2. np.ones(5):")
data = np.ones(5)
print(data , data.dtype)
data = np.ones(5, dtype=np.int32)
print(data, data.dtype)

2. np.ones(5):
[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] int32


In [42]:
# 3. np.empty(shape)
# shape 만큼 임의의 값으로 채워짐 ==> 임의의 값으로 초기화 시킨 것
print("3. np.empty(3)")
data = np.empty(3)
print(data , data.dtype)
data = np.empty(3, dtype=np.int32)
print(data , data.dtype)

3. np.empty(3)
[10. 20. 30.] float64
[5 3 8] int32


In [43]:
# 4. np.full(shape, 값)
# shape 만큼 지정된 값으로 채워짐
print("4. full(5, 10)")
data = np.full(5, 10)
print(data)

4. full(5, 10)
[10 10 10 10 10]


#### 5. np.arange

In [46]:
print("1. arange(10)")
data = np.arange(10)  # [0,10) 형식으로 표현
print(data)

print("2. arange(1,11)")
data = np.arange(1,11) # [1,11)형식으로 표현
print(data)

print("3. arange(1,11,2)")
data = np.arange(1,11,2) # start, end(exclusive), step
print(data)

1. arange(10)
[0 1 2 3 4 5 6 7 8 9]
2. arange(1,11)
[ 1  2  3  4  5  6  7  8  9 10]
3. arange(1,11,2)
[1 3 5 7 9]


In [47]:
# float값으로 설정하기
print("4. float으로 설정1")
data = np.arange(5, dtype=np.float32)
print(data) # [0. 1. 2. 3. 4.]

print("4. float으로 설정2")
# float값 지정하면 float 값 반환됨.
data = np.arange(5.0)
print(data) # [0. 1. 2. 3. 4.]

4. float으로 설정1
[0. 1. 2. 3. 4.]
4. float으로 설정2
[0. 1. 2. 3. 4.]


#### 6. np.linspace
- np.linspace(start, stop, [num=50, endpoint=True])
- 기본적으로 stop값이 범위에 포함되고, 포함시키지 않으려면 endpoint=Flase로 지정한다.

In [50]:
print("1. np.linspace(0, 1, 11)")
# 0 <= 값 <= 1 사이의 값을 11개 생성
data = np.linspace(0, 1, 11 )
print(data, data.dtype)

print("2. np.linspace(0, 0.9, 10)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10)
print(data)

print("3. np.linspace(0, 0.9, 10, endpoint=False)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10, endpoint=False)
print(data)

1. np.linspace(0, 1, 11)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] float64
2. np.linspace(0, 0.9, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
3. np.linspace(0, 0.9, 10, endpoint=False)
[0.   0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81]


#### 7. 벡터 삭제
arr = np.delete(arr, idx|fancy|slice, axis )

      - 삭제된 새로운 배열을 반환(in-place false, 원본이 유지된다.)
      - 순방향, 역방향 모두 가능
      - axis=None 이면 flatten 적용됨. => 다차원이 1차원으로 변경
      - slice인 경우에는  np.s_[::2]  형식 사용한다.

In [55]:
# 1. idx|fancy|slice 삭제
print("1. idx로 삭제")
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr,0)
print(new_arr)
new_arr = np.delete(arr,1)
print(new_arr)
new_arr = np.delete(arr,-1)
print(new_arr)

print("2. fancy 삭제") #  [idx, idx2, idx3] 여러 idx를 지정하는 방식. numpy에만 지원
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, [0,3,5] ) # fancy 인덱싱(정수배열 인덱싱)
print(new_arr)
new_arr = np.delete(arr, [0,3,5,-2] )
print(new_arr)

print("3. slice 삭제,  np.s_[::2]") # 대괄호만 쓰면 error 발생
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, np.s_[0:4] ) # slice 삭제
print(new_arr)

1. idx로 삭제
[9 8 7 5 4 3]
[8 7 5 4 3]
[9 7 5 4 3]
[9 8 7 5 4]
2. fancy 삭제
[9 8 7 5 4 3]
[8 7 4]
[8 7]
3. slice 삭제,  np.s_[::2]
[9 8 7 5 4 3]
[4 3]


In [59]:
# 2. 값으로 삭제하는 방법
arr = np.array([9,8,7,5,4,3])

print(np.where(arr == 5))
print(np.where((arr == 5)|(arr==8)))
print(np.where((arr == 5)|(arr==8)|(arr==3)))

xx = np.delete(arr, np.where(arr == 5)) # 5 값 삭제,
print(arr)
print(xx)

xx = np.delete(arr, np.where((arr==5)|(arr==8))) # 5 와 8 값 삭제,
print(arr)
print(xx)

(array([3], dtype=int64),)
(array([1, 3], dtype=int64),)
(array([1, 3, 5], dtype=int64),)
[9 8 7 5 4 3]
[9 8 7 4 3]
[9 8 7 5 4 3]
[9 7 4 3]


#### 8. 벡터 추가 및 삽입
    - 추가: arr = np.append(arr, values, axis=None)
    - 삽입: arr = np.insert(arr, idx|fancy|slice, value, axis)

In [60]:
#  1. ndarray 추가
arr = np.array([9,8,7,5,4,3])
new_arr = np.append(arr, [1,2,3])
print(arr)
print(new_arr)

[9 8 7 5 4 3]
[9 8 7 5 4 3 1 2 3]


In [62]:
#  2. ndarray 삽입

# 가. idx 이용
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, 0, [1,2,3])
print(arr)
print(new_arr)

# 나. fancy 이용: 1대1 대응으로 삽입됨
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, [0,3,1], [1,2,3])  # 0->1 , 3->2, 1->3 삽입됨. 따라서 갯수가 일치해야 된다.
print(arr)        #  [9 8 7 5 4 3]
                  #   1 9 8 7 5 4 3  <- 0에 1 삽입후
                  #   1 9 8 7 2 5 4 3  <- 3에 2 삽입후
                  #   1 9 3 8 7 2 5 4 3  <- 1에 3 삽입후
print(new_arr)    #  [1 9 3 8 7 2 5 4 3]

# 다. slice 이용
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, np.s_[0:2], [1,2])
print(arr)  # [9 8 7 5 4 3]
            #  1 9 8 7 5 4 3 <- 0에 1 삽입후
            #  1 9 2 8 7 5 4 3 <- 1에 2 삽입후
print(new_arr)  # [1 9 2 8 7 5 4 3]

[9 8 7 5 4 3]
[1 2 3 9 8 7 5 4 3]
[9 8 7 5 4 3]
[1 9 3 8 7 2 5 4 3]
[9 8 7 5 4 3]
[1 9 2 8 7 5 4 3]


### 2차원 배열

#### 1. 2차원 배열(행렬) 생성

In [70]:
# 1) np.array(중첩리스트) 이용
arr1 = [[1,2,3],[4,5,6]]
arr2D = np.array(arr1)
print("1. 2차원 행렬 생성: \n", arr2D, type(arr2D))
print()

# 2) 1차원을 2차원으로 변경, shape 속성 사용 / 중요
arr1D = np.array([1,2,3,4,5,6])
print('arr1D:', arr1D, '\n')

arr1D.shape=(2, 3) # 행 * 열 = ndarray 크기와 일치되어야 함
print("2. 1차원을 2차원으로 변경: \n", arr1D) # [[1 2 3][4 5 6]]
print()
arr1D.shape=(2, -1) # 행크기에 의해서 열크기가 자동 지정됨
print("2. 1차원을 2차원으로 변경: \n", arr1D) # [[1 2 3][4 5 6]]
print()
arr1D.shape=(-1, 2)   # 열크기에 의해서 행크기가 자동 지정됨
print("2. 1차원을 2차원으로 변경: \n", arr1D)
print()

1. 2차원 행렬 생성: 
 [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>

arr1D: [1 2 3 4 5 6] 

2. 1차원을 2차원으로 변경: 
 [[1 2 3]
 [4 5 6]]

2. 1차원을 2차원으로 변경: 
 [[1 2 3]
 [4 5 6]]

2. 1차원을 2차원으로 변경: 
 [[1 2]
 [3 4]
 [5 6]]



In [76]:
# 다차원 shape 해석하기 -> 맨 뒤부터 읽어가면서 그림을 그리며 해석하기
arr1D = np.array([1,2,3,4,5,6])
arr1D.shape= (2, 3, 1)
print(arr1D, '\n')
arr1D.shape= (3, 1, 2)
print(arr1D)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 

[[[1 2]]

 [[3 4]]

 [[5 6]]]


#### 2. 속성

In [77]:
arr1 = [[1, 2, 3], [4, 5, 6]]
arr2D = np.array(arr1)
print(vector1, type(vector1), vector1.dtype)

print("1. 2차원 행렬 생성: \n", arr2D, type(arr2D))
print("1. 행렬의 차원(dimension,axis)갯수:", arr2D.ndim)
print("2. 행렬의 각 차원의 크기(shape):", arr2D.shape) # tuple로 반환된다.
print("3. 행렬의 총 요소 갯수(size):", arr2D.size)
print("4. 행렬의 저장 데이터 type(dtype):", arr2D.dtype)

[10 20 30] <class 'numpy.ndarray'> int32
1. 2차원 행렬 생성: 
 [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
1. 벡터의 차원(dimension,axis)갯수: 2
2. 벡터의 각 차원의 크기(shape): (2, 3)
3. 벡터의 총 요소 갯수(size): 6
4. 벡터의 저장 데이터 type(dtype): int32


#### 3. 랜덤함수로 행렬 생성

In [78]:
# 1) 랜덤값 고정
np.random.seed(1234)

# 2) np.random.random(size=(행,열))
print("1. random(size=(행,열))")
arr = np.random.random()
arr = np.random.random(size=(2, 3))
print(arr, type(arr), arr.dtype)

1. random(size=(행,열))
[[0.62210877 0.43772774 0.78535858]
 [0.77997581 0.27259261 0.27646426]] <class 'numpy.ndarray'> float64


In [81]:
# 3) np.random.rand(행, 열)
# 0 ~ 1의 균등분포에서 표본 추출. 갯수 생략하면  1개반환
print("2. rand(2, 3)")
arr = np.random.rand(2, 3)
print(arr, type(arr), arr.dtype)

2. rand(행, 열)
[[0.71270203 0.37025075 0.56119619]
 [0.50308317 0.01376845 0.77282662]] <class 'numpy.ndarray'> float64


In [82]:
# 3) np.random.randn(행, 열)
# 표준편차가 1이고 평균값이 0인 정규분포에서 표본 추출. 갯수 생략하면  1개반환
print("3. randn(2, 3)")
arr = np.random.randn(2, 3)
print(arr)

3. randn(5)
[[-0.30426018  0.861661   -0.68992667]
 [ 0.18749737  0.60430874 -0.18301422]]


In [83]:
# 4) np.random.randint(low, high, size=(행, 열))
# 주어진 최소/최대 범위 안에서 임의의 난수 n개 추출
print("4. randint(1,10,size=(2, 3))")
arr = np.random.randint(1,10,size=(2, 3))
print(arr)

4. randint(1,10,size=(2, 3))
[[2 4 2]
 [4 8 2]]


In [84]:
# 4) np.random.randint(high, size=(행, 열))
# 0 ~ 최대(exclusive) 범위안에서 임의의 정수 n개 반환, 복원추출
print("4. randint(5, size=(2, 3)): ")
arr = np.random.randint(5, size=(2, 3))
print(arr)

4. randint(5, size=(2, 3)): 
[[4 0 4]
 [1 1 4]]


#### 4. 특정 값으로 행렬 생성

In [87]:
# 1. np.zeros((행, 열))
# shape만큼 0으로 채움. 기본 type은 float64
print("1. np.zeros((2, 3)):")
data = np.zeros((2, 3))
print(data, data.dtype, '\n')
data = np.zeros((2, 3), dtype=np.int32)
print(data, data.dtype)

1. np.zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]] float64 

[[0 0 0]
 [0 0 0]] int32


In [91]:
# 2. np.ones((행, 열))
# shape만큼  1.0 으로 채움. 기본 type은 float64
print("2. np.ones((2, 3)):")
data = np.ones((2, 3))
print(data , data.dtype)
data = np.ones((2, 3), dtype=np.int32)
print(data, data.dtype)

2. np.ones((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1 1 1]
 [1 1 1]] int32


In [90]:
# 3. np.empty((행, 열))
# shape 만큼 임의의 값으로 채워짐 ==> 임의의 값으로 초기화 시킨 것
print("3. np.empty((2, 3))")
data = np.empty((2, 9))
print(data , data.dtype)
data = np.empty((2, 9), dtype=np.int32)
print(data , data.dtype)

3. np.empty(3)
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.39077217e-307
  1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306
  1.37962320e-306]
 [1.29060871e-306 2.22518251e-306 1.33511969e-306 1.78022342e-306
  1.05700345e-307 3.11525958e-307 8.90092016e-307 1.24611062e-306
  1.42410974e-306]] float64
[[ 1889785610  1068960317  1889785610  1070008893   343597384  1070679982
   1889785610  1071057469  -858993460]
 [ 1071434956   343597384  1071728558 -1030792151  1071917301  1889785610
   1072106045   515396075  1072294789]] int32


In [92]:
# 4. np.full((행, 열), 값)
# shape 만큼 지정된 값으로 채워짐
print("4. full((2, 3), 10)")
data = np.full((2, 3), 10)
print(data)

4. full((2, 3), 10)
[[10 10 10]
 [10 10 10]]


#### 5. arange + reshape 사용하여 행렬 생성

In [93]:
# 1차원 벡터를 reshape를 이용해 2차원 행렬 생성
print("1. arange(10)")
data = np.arange(10).reshape((2, 5))
print(data)

1. arange(10)
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 6. 행렬 삭제
    - arr = np.delete(arr, idx|fancy|slice, axis)
    - axis = None: flatten / axis = 0: 행 제거 / axis = 1: 열 제거

In [94]:
arr2D = np.arange(25).reshape(5,5)
print(arr2D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


##### axis 미지정(None)

In [95]:
# 1. idx 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, -1)
print(xxx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [96]:
# 2. fancy 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, [0,-1])
print(xxx)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [97]:
# 3. slice 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, np.s_[:8])
print(xxx)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


##### axis = 0

In [98]:
# 4. idx + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, -1, axis=0)
print(xxx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [99]:
# 5. fancy + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, [0,-1], axis=0)
print(xxx)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [100]:
# 6. slice + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, np.s_[:3], axis=0)
print(xxx)

[[15 16 17 18 19]
 [20 21 22 23 24]]


##### axis = 1

In [101]:
# 7. idx + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, -1, axis=1)
print(xxx)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [102]:
# 8. fancy + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, [0,-1], axis=1)
print(xxx)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


In [103]:
# 9. slice + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, np.s_[:3], axis=1)
print(xxx)

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


#### 7. 행렬 추가 및 삽입
    - 벡터와 차이점은 axis 지정 여부에 따라 출력이 달라진다.

In [108]:
arr = np.array([[1,2,3],[4,5,6]])

# 1. append 함수
# 1) axis=None 지정한 추가
# 2차원에서 axis 지정하지 않으면 flatten 되어 추가됨. 따라서 dimension 일치하지 않아도 된다.
xxx = np.append(arr, [100,200,300,400])
print(xxx, '\n')

# 2) axis=0 지정한 추가 ==> 행 추가
xxx = np.append(arr, [[100,200,300]], axis=0)
print(xxx, '\n')

# 3) axis=1 지정한 추가 ==> 열 추가
xxx = np.append(arr, [[100],[200]], axis=1)
print(xxx)

[  1   2   3   4   5   6 100 200 300 400] 

[[  1   2   3]
 [  4   5   6]
 [100 200 300]] 

[[  1   2   3 100]
 [  4   5   6 200]]


In [109]:
# 2. insert 함수
arr = np.array([[1,2,3],[4,5,6]])

# 1) axis=None 지정한 삽입
# 2차원에서 axis 지정하지 않으면 flatten 되어 추가됨. 따라서 dimension 일치하지 않아도 된다.
xxx = np.insert(arr, 0,  [100,200,300,400])
print(xxx, '\n')

# 2) axis=0 지정한 삽입 ==> 행 삽입
xxx = np.insert(arr, 0,  [[100,200,300]], axis=0)
print(xxx, '\n')

# 3) axis=1 지정한 삽입 ==> 열 삽입
xxx = np.insert(arr, 0, [[100],[200]], axis=1)
print(xxx)

[100 200 300 400   1   2   3   4   5   6] 

[[100 200 300]
 [  1   2   3]
 [  4   5   6]] 

[[100 200   1   2   3]
 [100 200   4   5   6]]


### Type 변환
- 다차원 배열의 모든 요소가 한꺼번에 변경된다.(벡터 연산)
    - dtype 속성 이용
    - astype 함수 이용(많이 사용)

In [110]:
# 1. int32 --> float64으로
data = [10,20,30]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.float64)
arr3 = arr1.astype(np.float64)
print("1. 원본 데이터: ", arr1.dtype , arr1)
print("2. int값을 float으로 변경 1: ", arr2.dtype , arr2)
print("2. int값을 float으로 변경 2: ", arr3.dtype , arr3)

1. 원본 데이터:  int32 [10 20 30]
2. int값을 float으로 변경 1:  float64 [10. 20. 30.]
2. int값을 float으로 변경 2:  float64 [10. 20. 30.]


In [113]:
# 2. float --> int 으로
data = [10.5, 20.7, 30.23, 100]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.int64)
arr3 = arr1.astype(np.int64)
print("3. 원본 데이터: ", arr1.dtype , arr1)
print("4. float 값을 int 으로 변경 1: ", arr2.dtype , arr2)
print("4. float 값을 int 으로 변경 2: ", arr3.dtype , arr3)

3. 원본 데이터:  float64 [ 10.5   20.7   30.23 100.  ]
4. float 값을 int 으로 변경 1:  int64 [ 10  20  30 100]
4. float 값을 int 으로 변경 2:  int64 [ 10  20  30 100]


In [116]:
# 3. int --> bytes , str
data = [10,20,30]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.string_)  # bytes 타입,  np.string 안됨.
arr3 = arr1.astype(np.string_)
arr4 = np.array(data , dtype=np.str_)   # str 타입 , dtype=np.str 안됨.
arr5 = arr1.astype(np.str_)
print("5. 원본 데이터: ", arr1.dtype , arr1)
print("6. int 값을 bytes 으로 변경 1: ", arr2.dtype , arr2)
print("6. int 값을 bytes 으로 변경 2: ", arr3.dtype , arr3)
print("7. int 값을 str 으로 변경 : ", arr4.dtype , arr4)
print("7. int 값을 str 으로 변경 : ", arr5.dtype , arr5)

# print(dir(np))

5. 원본 데이터:  int32 [10 20 30]
6. int 값을 bytes 으로 변경 1:  |S2 [b'10' b'20' b'30']
6. int 값을 bytes 으로 변경 2:  |S11 [b'10' b'20' b'30']
7. int 값을 str 으로 변경 :  <U2 ['10' '20' '30']
7. int 값을 str 으로 변경 :  <U11 ['10' '20' '30']


In [119]:
# 4. str --> int
data =['10','20','30']
arr1 = np.array(data)
print("원본:", arr1, arr1.dtype)
arr2 = arr1.astype(np.int32)
print("8. str 값을 int 으로 변경 :", arr2, arr2.dtype) # [10 20 30]

arr3 = np.array(data).astype(np.int32)
print(arr3, arr2.dtype) # [10 20 30]

원본: ['10' '20' '30'] <U2
8. str 값을 int 으로 변경 : [10 20 30] int32
[10 20 30] int32


### 벡터 연산

In [120]:
# 1. 기본 파이썬 연산
print("1. 파이썬의 리스트 + 리스트")
print([10,20,30]+[10,20,30])

print("2. 기본 파이썬의 리스트 + 스칼라")
# print([10,20,30] + 2)  # TypeError: can only concatenate list (not "int") to list
print([10,20,30] * 3)

1. 파이썬의 리스트 + 리스트
[10, 20, 30, 10, 20, 30]
2. 기본 파이썬의 리스트 + 스칼라
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [121]:
# 2. 다차원 배열 + 다차원 배열 ==> 요소간 연산, 반드시 shape 일치해야 된다.
arr1D_1 = np.array([10,20,30])
arr1D_2 = np.array([5,4,3])
print("3. numpy의 벡터간 연산 처리")
print(arr1D_1 + arr1D_2)
print(arr1D_1 - arr1D_2)
print(arr1D_1 * arr1D_2)
print(arr1D_1 / arr1D_2)

3. numpy의 벡터간 연산 처리
[15 24 33]
[ 5 16 27]
[50 80 90]
[ 2.  5. 10.]


In [122]:
# 3. 백터 + 스칼라 ==> 자동으로 브로드캐스팅(개수를 맞춰줌) 되어 연산됨.
# 브로드캐스팅(broadcasting): 서로 다른 차원을 가지고 있는 두 개의 값을 산술하는 도중에
# 연산이 가능하도록 차원을 자동으로 맞추어 주는 작업을 의미한다.
arr1D_1 = np.array([10,20,30])
print("4. numpy의 벡터 + 스칼라 연산 처리")
print(arr1D_1 + 2)
print(arr1D_1 - 2)
print(arr1D_1 * 2)
print(arr1D_1 / 2)

4. numpy의 벡터 + 스칼라 연산 처리
[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]


In [125]:
# 4. 비교 연산도 벡터화 가능
print("5. 벡터의 비교 연산처리1: ", arr1D_1%3 == 0)
print("5. 벡터의 비교 연산처리2: ", arr1D_1 > 15)
print("5. 벡터의 비교 연산처리3: ", (arr1D_1 > 15) & ( arr1D_1%6 == 0))

5. 벡터의 비교 연산처리1:  [False False  True]
5. 벡터의 비교 연산처리2:  [False  True  True]
5. 벡터의 비교 연산처리3:  [False False  True]


### 색인

#### 1. 1차원 배열(벡터) 색인

In [145]:
arr = np.arange(10)
print("원본:", arr)

# 1. 인덱싱
print("1. 인덱싱:", arr[0], arr[-1])

# 2. 슬라이싱
print("2. 슬라이싱:", arr[1:5], arr[:5], arr[1:], arr[1:10:2], arr[:], arr[...]) # [...]은 numpy에서만 지원

원본: [0 1 2 3 4 5 6 7 8 9]
1. 인덱싱: 0 9
2. 슬라이싱: [1 2 3 4] [0 1 2 3 4] [1 2 3 4 5 6 7 8 9] [1 3 5 7 9] [0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [146]:
# 3. fancy 색인
data = np.arange(10) * 100
print("3. original:", data)
# print(data[1, 3, 5]) -> error
print("3-1. fancy data[[1, 3, 5]]:", data[[1, 3, 5]])
print("3-2. fancy data[[8, 1, 5]]:", data[[8, 1, 5]])

3. original: [  0 100 200 300 400 500 600 700 800 900]
3-1. fancy data[[1, 3, 5]]: [100 300 500]
3-2. fancy data[[8, 1, 5]]: [800 100 500]


In [144]:
# 4. boolean 색인 -> True의 결과값을 가진 요소만 나온다, 반드시 색인 대상과 길이가 같아야 함
data = np.array([1,2,3,4,5])
print("4. original: " , data)
print("4-1. 벡터연산,  data%2==0: " , data%2==0)
print("4-2. boolean 색인, [True,True,True,True,False]:",data[[True,True,True,True,False]])
print("4-3. boolean 색인 활용, data[data%2==0]:",data[data%2==0])
print("4-4. boolean 색인 활용, data[data > 3 ]:",data[data > 3])
print("4-5. boolean 색인의 & 연산자:" , data[(data%2==0) & (data >2)]) 
print("4-6. boolean 색인의 | 연산자" , data[(data%2!=0) | (data < 4)])
print("4-7. boolean 색인 활용, data[data > 3 ]:",data[~(data > 3)])

4. original:  [1 2 3 4 5]
4-1. 벡터연산,  data%2==0:  [False  True False  True False]
4-2. boolean 색인, [True,True,True,True,False]: [1 2 3 4]
4-3. boolean 색인 활용, data[data%2==0]: [2 4]
4-4. boolean 색인 활용, data[data > 3 ]: [4 5]
4-5. boolean 색인의 & 연산자: [4]
4-6. boolean 색인의 | 연산자 [1 2 3 5]
4-7. boolean 색인 활용, data[data > 3 ]: [1 2 3]


In [151]:
# 실습: 특정 이름 검색
names = np.array(['홍길동', '세종',"홍길동","이순신","정조","홍길동"])

# 홍길동
print(names[names=='홍길동'])
print([i for i in names if i=='홍길동'])

['홍길동' '홍길동' '홍길동']
['홍길동', '홍길동', '홍길동']
