## 6/9(금)

### numpy 작동 확인
- uninstall 방법 `pip uninstall numpy`

In [2]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


### 1차원 배열

#### 1. 1차원 배열 생성

In [3]:
# 배열 생성: np.array() 사용

list_value = [10,20,30]  # list, tuple, set , 정수의 기본 dtype은  int32 ( 4byte )
vector1 = np.array(list_value)
print(list_value, type(list_value))
print(vector1, type(vector1), vector1.dtype)

[10, 20, 30] <class 'list'>
[10 20 30] <class 'numpy.ndarray'> int32


In [4]:
list_value = [10.,20.,30.]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [5]:
# upcasting: 자동으로 큰 데이터 타입으로 변경되는 것
list_value = [10.,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [8]:
# 명시적으로 데이터 타입을 변경 가능
list_value = [10.,20.,30.]
vector1 = np.array(list_value, dtype=np.int32)
print(vector1, type(vector1), vector1.dtype)

[10 20 30] <class 'numpy.ndarray'> int32


#### 2. ndarray의 속성

In [46]:
list_value = [10,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

# print(dir(vector1))

# 'T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 
# 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 
# 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 
# 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 
# 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 
# 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 
# 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'

# print(dir(np))

# 'ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 
# 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 
# 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 
# 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__',
# '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__',
# '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names',
# '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg',
# '_version', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis',
# 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 
# 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray', 'asarray_chkfinite', 'ascontiguousarray', 'asfarray', 'asfortranarray',
# 'asmatrix', 'atleast_1d', 'atleast_2d', 'atleast_3d', 'average', 'bartlett', 'base_repr', 'binary_repr', 'bincount', 'bitwise_and', 'bitwise_not', 'bitwise_or', 'bitwise_xor', 'blackman',
# 'block', 'bmat', 'bool_', 'broadcast', 'broadcast_arrays', 'broadcast_shapes', 'broadcast_to', 'busday_count', 'busday_offset', 'busdaycalendar', 'byte', 'byte_bounds', 'bytes_', 'c_',
# 'can_cast', 'cast', 'cbrt', 'cdouble', 'ceil', 'cfloat', 'char', 'character', 'chararray', 'choose', 'clip', 'clongdouble', 'clongfloat', 'column_stack', 'common_type', 'compare_chararrays', 
# 'compat', 'complex128', 'complex64', 'complex_', 'complexfloating', 'compress', 'concatenate', 'conj', 'conjugate', 'convolve', 'copy', 'copysign', 'copyto', 'corrcoef', 'correlate', 'cos',
# 'cosh', 'count_nonzero', 'cov', 'cross', 'csingle', 'ctypeslib', 'cumprod', 'cumproduct', 'cumsum', 'datetime64', 'datetime_as_string', 'datetime_data', 'deg2rad', 'degrees', 'delete', 
# 'deprecate', 'deprecate_with_doc', 'diag', 'diag_indices', 'diag_indices_from', 'diagflat', 'diagonal', 'diff', 'digitize', 'disp', 'divide', 'divmod', 'dot', 'double', 'dsplit', 'dstack',
# 'dtype', 'e', 'ediff1d', 'einsum', 'einsum_path', 'emath', 'empty', 'empty_like', 'equal', 'errstate', 'euler_gamma', 'exp', 'exp2', 'expand_dims', 'expm1', 'extract', 'eye', 'fabs',
# 'fastCopyAndTranspose', 'fft', 'fill_diagonal', 'find_common_type', 'finfo', 'fix', 'flatiter', 'flatnonzero', 'flexible', 'flip', 'fliplr', 'flipud', 'float16', 'float32', 'float64',
# 'float_', 'float_power', 'floating', 'floor', 'floor_divide', 'fmax', 'fmin', 'fmod', 'format_float_positional', 'format_float_scientific', 'format_parser', 'frexp', 'from_dlpack', 'frombuffer',
# 'fromfile', 'fromfunction', 'fromiter', 'frompyfunc', 'fromregex', 'fromstring', 'full', 'full_like', 'gcd', 'generic', 'genfromtxt', 'geomspace', 'get_array_wrap', 'get_include',
# 'get_printoptions', 'getbufsize', 'geterr', 'geterrcall', 'geterrobj', 'gradient', 'greater', 'greater_equal', 'half', 'hamming', 'hanning', 'heaviside', 'histogram', 'histogram2d',
# 'histogram_bin_edges', 'histogramdd', 'hsplit', 'hstack', 'hypot', 'i0', 'identity', 'iinfo', 'imag', 'in1d', 'index_exp', 'indices', 'inexact', 'inf', 'info', 'infty', 'inner', 'insert', 
# 'int16', 'int32', 'int64', 'int8', 'int_', 'intc', 'integer', 'interp', 'intersect1d', 'intp', 'invert', 'is_busday', 'isclose', 'iscomplex', 'iscomplexobj', 'isfinite', 'isfortran', 'isin', 
# 'isinf', 'isnan', 'isnat', 'isneginf', 'isposinf', 'isreal', 'isrealobj', 'isscalar', 'issctype', 'issubclass_', 'issubdtype', 'issubsctype', 'iterable', 'ix_', 'kaiser', 'kron', 'lcm', 'ldexp',
# 'left_shift', 'less', 'less_equal', 'lexsort', 'lib', 'linalg', 'linspace', 'little_endian', 'load', 'loadtxt', 'log', 'log10', 'log1p', 'log2', 'logaddexp', 'logaddexp2', 'logical_and',
# 'logical_not', 'logical_or', 'logical_xor', 'logspace', 'longcomplex', 'longdouble', 'longfloat', 'longlong', 'lookfor', 'ma', 'mask_indices', 'mat', 'math', 'matmul', 'matrix', 'max', 'maximum',
# 'maximum_sctype', 'may_share_memory', 'mean', 'median', 'memmap', 'meshgrid', 'mgrid', 'min', 'min_scalar_type', 'minimum', 'mintypecode', 'mod', 'modf', 'moveaxis', 'msort', 'multiply',
# 'nan', 'nan_to_num', 'nanargmax', 'nanargmin', 'nancumprod', 'nancumsum', 'nanmax', 'nanmean', 'nanmedian', 'nanmin', 'nanpercentile', 'nanprod', 'nanquantile', 'nanstd', 'nansum', 'nanvar',
# 'nbytes', 'ndarray', 'ndenumerate', 'ndim', 'ndindex', 'nditer', 'negative', 'nested_iters', 'newaxis', 'nextafter', 'nonzero', 'not_equal', 'numarray', 'number', 'obj2sctype', 'object_',
# 'ogrid', 'oldnumeric', 'ones', 'ones_like', 'outer', 'packbits', 'pad', 'partition', 'percentile', 'pi', 'piecewise', 'place', 'poly', 'poly1d', 'polyadd', 'polyder', 'polydiv', 'polyfit',
# 'polyint', 'polymul', 'polynomial', 'polysub', 'polyval', 'positive', 'power', 'printoptions', 'prod', 'product', 'promote_types', 'ptp', 'put', 'put_along_axis', 'putmask', 'quantile', 'r_',
# 'rad2deg', 'radians', 'random', 'ravel', 'ravel_multi_index', 'real', 'real_if_close', 'rec', 'recarray', 'recfromcsv', 'recfromtxt', 'reciprocal', 'record', 'remainder', 'repeat', 'require', 
# 'reshape', 'resize', 'result_type', 'right_shift', 'rint', 'roll', 'rollaxis', 'roots', 'rot90', 'round', 'round_', 'row_stack', 's_', 'safe_eval', 'save', 'savetxt', 'savez', 'savez_compressed',
# 'sctype2char', 'sctypeDict', 'sctypes', 'searchsorted', 'select', 'set_numeric_ops', 'set_printoptions', 'set_string_function', 'setbufsize', 'setdiff1d', 'seterr', 'seterrcall', 'seterrobj',
# 'setxor1d', 'shape', 'shares_memory', 'short', 'show_config', 'show_runtime', 'sign', 'signbit', 'signedinteger', 'sin', 'sinc', 'single', 'singlecomplex', 'sinh', 'size', 'sometrue', 'sort',
# 'sort_complex', 'source', 'spacing', 'split', 'sqrt', 'square', 'squeeze', 'stack', 'std', 'str_', 'string_', 'subtract', 'sum', 'swapaxes', 'take', 'take_along_axis', 'tan', 'tanh', 'tensordot',
# 'test', 'testing', 'tile', 'timedelta64', 'trace', 'tracemalloc_domain', 'transpose', 'trapz', 'tri', 'tril', 'tril_indices', 'tril_indices_from', 'trim_zeros', 'triu', 'triu_indices',
# 'triu_indices_from', 'true_divide', 'trunc', 'typecodes', 'typename', 'ubyte', 'ufunc', 'uint', 'uint16', 'uint32', 'uint64', 'uint8', 'uintc', 'uintp', 'ulonglong', 'unicode_', 'union1d',
# 'unique', 'unpackbits', 'unravel_index', 'unsignedinteger', 'unwrap', 'use_hugepage', 'ushort', 'vander', 'var', 'vdot', 'vectorize', 'version', 'void', 'vsplit', 'vstack', 'where', 'who',
# 'zeros', 'zeros_like'

[10 20 30] <class 'numpy.ndarray'> int32


In [63]:
print("1. 벡터의 차원(dimension,axis)갯수:", vector1.ndim)
print("2. 벡터의 각 차원의 크기(shape):", vector1.shape) # tuple로 반환된다.
print("3. 벡터의 총 요소 갯수(size):", vector1.size)
print("4. 벡터의 저장 데이터 type(dtype):", vector1.dtype)

1. 벡터의 차원(dimension,axis)갯수: 1
2. 벡터의 각 차원의 크기(shape): (3,)
3. 벡터의 총 요소 갯수(size): 3
4. 벡터의 저장 데이터 type(dtype): int32


#### 3. 랜덤함수로 벡터 생성

In [16]:
# 1) 랜덤값 고정
np.random.seed(1234)

# 2) np.random.random([갯수])
# 0.0 <= 값 < 1.0 사이의 임의의 float 5개 랜덤값 반환. 갯수 생략하면  1개반환
print("1. random(5)")
arr = np.random.random()
arr = np.random.random(5)
print(arr, type(arr), arr.dtype)

1. random(5)
[0.62210877 0.43772774 0.78535858 0.77997581 0.27259261] <class 'numpy.ndarray'> float64


In [19]:
# 3) np.random.rand([갯수])
# 0 ~ 1의 균등분포에서 표본 추출. 갯수 생략하면  1개반환
print("2. rand(5)")
arr = np.random.rand()
arr = np.random.rand(5)
print(arr, type(arr), arr.dtype)

2. rand(5)
[0.37025075 0.56119619 0.50308317 0.01376845 0.77282662] <class 'numpy.ndarray'> float64


In [22]:
# 3) np.random.randn([갯수])
# 표준편차가 1이고 평균값이 0인 정규분포에서 표본 추출. 갯수 생략하면  1개반환
print("3. randn(5)")
arr = np.random.randn()
arr = np.random.randn(5)
print(arr)

3. randn(5)
[-0.28694235  0.44143825 -0.76987271 -0.97456841  0.70900741]


In [28]:
# 4) np.random.randint(low, high, n)
# 주어진 최소/최대 범위 안에서 임의의 난수 n개 추출
print("4. randint(1,10,3)")
arr = np.random.randint(1,10,3)
print(arr)

4. randint(1,10,3)
[5 3 8]


In [31]:
# 4) np.random.randint(high, size=n)
# 0 ~ 최대(exclusive) 범위안에서 임의의 정수 n개 반환, 복원추출
print("4. randint(5, size=4): ")
arr = np.random.randint(5, size=4)
print(arr)

4. randint(5, size=4): 
[2 1 2 1]


In [34]:
# 5) np.random.choice(리스트)
# 주어진 리스트에서 임의의 값 1개 반환
print("5. np.random.choice(['foo','bar','baz'])")
choice_value = np.random.choice(['foo','bar','baz'])
print(choice_value)

5. np.random.choice(['foo','bar','baz'])
bar


In [35]:
# 6) np.random.shuffle(리스트)
# 주어진 리스트를 shuffle 함.  in-place(True)로 동작됨.
print("6. np.random.shuffle(1,3,56,7,98])")
shuffle_value = [1,3,56,7,98]
np.random.shuffle(shuffle_value)
print(shuffle_value)

6. np.random.shuffle(1,3,56,7,98])
[56, 1, 3, 7, 98]


#### 4. 특정 값으로 벡터를 생성

In [37]:
# 1. np.zeros(shape)
# shape만큼 0으로 채움. 기본 type은 float64
print("1. np.zeros(5):")
data = np.zeros(5)
print(data, data.dtype)
data = np.zeros(5, dtype=np.int32)
print(data, data.dtype)

1. np.zeros(5):
[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [38]:
# 2. np.ones(shape)
# shape만큼  1.0 으로 채움. 기본 type은 float64
print("2. np.ones(5):")
data = np.ones(5)
print(data , data.dtype)
data = np.ones(5, dtype=np.int32)
print(data, data.dtype)

2. np.ones(5):
[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] int32


In [42]:
# 3. np.empty(shape)
# shape 만큼 임의의 값으로 채워짐 ==> 임의의 값으로 초기화 시킨 것
print("3. np.empty(3)")
data = np.empty(3)
print(data , data.dtype)
data = np.empty(3, dtype=np.int32)
print(data , data.dtype)

3. np.empty(3)
[10. 20. 30.] float64
[5 3 8] int32


In [43]:
# 4. np.full(shape, 값)
# shape 만큼 지정된 값으로 채워짐
print("4. full(5, 10)")
data = np.full(5, 10)
print(data)

4. full(5, 10)
[10 10 10 10 10]


#### 5. np.arange

In [46]:
print("1. arange(10)")
data = np.arange(10)  # [0,10) 형식으로 표현
print(data)

print("2. arange(1,11)")
data = np.arange(1,11) # [1,11)형식으로 표현
print(data)

print("3. arange(1,11,2)")
data = np.arange(1,11,2) # start, end(exclusive), step
print(data)

1. arange(10)
[0 1 2 3 4 5 6 7 8 9]
2. arange(1,11)
[ 1  2  3  4  5  6  7  8  9 10]
3. arange(1,11,2)
[1 3 5 7 9]


In [47]:
# float값으로 설정하기
print("4. float으로 설정1")
data = np.arange(5, dtype=np.float32)
print(data) # [0. 1. 2. 3. 4.]

print("4. float으로 설정2")
# float값 지정하면 float 값 반환됨.
data = np.arange(5.0)
print(data) # [0. 1. 2. 3. 4.]

4. float으로 설정1
[0. 1. 2. 3. 4.]
4. float으로 설정2
[0. 1. 2. 3. 4.]


#### 6. np.linspace
- np.linspace(start, stop, [num=50, endpoint=True])
- 기본적으로 stop값이 범위에 포함되고, 포함시키지 않으려면 endpoint=Flase로 지정한다.

In [50]:
print("1. np.linspace(0, 1, 11)")
# 0 <= 값 <= 1 사이의 값을 11개 생성
data = np.linspace(0, 1, 11 )
print(data, data.dtype)

print("2. np.linspace(0, 0.9, 10)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10)
print(data)

print("3. np.linspace(0, 0.9, 10, endpoint=False)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10, endpoint=False)
print(data)

1. np.linspace(0, 1, 11)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] float64
2. np.linspace(0, 0.9, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
3. np.linspace(0, 0.9, 10, endpoint=False)
[0.   0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81]


#### 7. 벡터 삭제
arr = np.delete(arr, idx|fancy|slice, axis )

      - 삭제된 새로운 배열을 반환(in-place false, 원본이 유지된다.)
      - 순방향, 역방향 모두 가능
      - axis=None 이면 flatten 적용됨. => 다차원이 1차원으로 변경
      - slice인 경우에는  np.s_[::2]  형식 사용한다.

In [55]:
# 1. idx|fancy|slice 삭제
print("1. idx로 삭제")
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr,0)
print(new_arr)
new_arr = np.delete(arr,1)
print(new_arr)
new_arr = np.delete(arr,-1)
print(new_arr)

print("2. fancy 삭제") #  [idx, idx2, idx3] 여러 idx를 지정하는 방식. numpy에만 지원
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, [0,3,5] ) # fancy 인덱싱(정수배열 인덱싱)
print(new_arr)
new_arr = np.delete(arr, [0,3,5,-2] )
print(new_arr)

print("3. slice 삭제,  np.s_[::2]") # 대괄호만 쓰면 error 발생
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, np.s_[0:4] ) # slice 삭제
print(new_arr)

1. idx로 삭제
[9 8 7 5 4 3]
[8 7 5 4 3]
[9 7 5 4 3]
[9 8 7 5 4]
2. fancy 삭제
[9 8 7 5 4 3]
[8 7 4]
[8 7]
3. slice 삭제,  np.s_[::2]
[9 8 7 5 4 3]
[4 3]


In [59]:
# 2. 값으로 삭제하는 방법
arr = np.array([9,8,7,5,4,3])

print(np.where(arr == 5))
print(np.where((arr == 5)|(arr==8)))
print(np.where((arr == 5)|(arr==8)|(arr==3)))

xx = np.delete(arr, np.where(arr == 5)) # 5 값 삭제,
print(arr)
print(xx)

xx = np.delete(arr, np.where((arr==5)|(arr==8))) # 5 와 8 값 삭제,
print(arr)
print(xx)

(array([3], dtype=int64),)
(array([1, 3], dtype=int64),)
(array([1, 3, 5], dtype=int64),)
[9 8 7 5 4 3]
[9 8 7 4 3]
[9 8 7 5 4 3]
[9 7 4 3]


#### 8. 벡터 추가 및 삽입
    - 추가: arr = np.append(arr, values, axis=None)
    - 삽입: arr = np.insert(arr, idx|fancy|slice, value, axis)

In [60]:
#  1. ndarray 추가
arr = np.array([9,8,7,5,4,3])
new_arr = np.append(arr, [1,2,3])
print(arr)
print(new_arr)

[9 8 7 5 4 3]
[9 8 7 5 4 3 1 2 3]


In [62]:
#  2. ndarray 삽입

# 가. idx 이용
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, 0, [1,2,3])
print(arr)
print(new_arr)

# 나. fancy 이용: 1대1 대응으로 삽입됨
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, [0,3,1], [1,2,3])  # 0->1 , 3->2, 1->3 삽입됨. 따라서 갯수가 일치해야 된다.
print(arr)        #  [9 8 7 5 4 3]
                  #   1 9 8 7 5 4 3  <- 0에 1 삽입후
                  #   1 9 8 7 2 5 4 3  <- 3에 2 삽입후
                  #   1 9 3 8 7 2 5 4 3  <- 1에 3 삽입후
print(new_arr)    #  [1 9 3 8 7 2 5 4 3]

# 다. slice 이용
arr = np.array([9,8,7,5,4,3])
new_arr = np.insert(arr, np.s_[0:2], [1,2])
print(arr)  # [9 8 7 5 4 3]
            #  1 9 8 7 5 4 3 <- 0에 1 삽입후
            #  1 9 2 8 7 5 4 3 <- 1에 2 삽입후
print(new_arr)  # [1 9 2 8 7 5 4 3]

[9 8 7 5 4 3]
[1 2 3 9 8 7 5 4 3]
[9 8 7 5 4 3]
[1 9 3 8 7 2 5 4 3]
[9 8 7 5 4 3]
[1 9 2 8 7 5 4 3]


### 2차원 배열

#### 1. 2차원 배열(행렬) 생성

In [70]:
# 1) np.array(중첩리스트) 이용
arr1 = [[1,2,3],[4,5,6]]
arr2D = np.array(arr1)
print("1. 2차원 행렬 생성: \n", arr2D, type(arr2D))
print()

# 2) 1차원을 2차원으로 변경, shape 속성 사용 / 중요
arr1D = np.array([1,2,3,4,5,6])
print('arr1D:', arr1D, '\n')

arr1D.shape=(2, 3) # 행 * 열 = ndarray 크기와 일치되어야 함
print("2. 1차원을 2차원으로 변경: \n", arr1D) # [[1 2 3][4 5 6]]
print()
arr1D.shape=(2, -1) # 행크기에 의해서 열크기가 자동 지정됨
print("2. 1차원을 2차원으로 변경: \n", arr1D) # [[1 2 3][4 5 6]]
print()
arr1D.shape=(-1, 2)   # 열크기에 의해서 행크기가 자동 지정됨
print("2. 1차원을 2차원으로 변경: \n", arr1D)
print()

1. 2차원 행렬 생성: 
 [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>

arr1D: [1 2 3 4 5 6] 

2. 1차원을 2차원으로 변경: 
 [[1 2 3]
 [4 5 6]]

2. 1차원을 2차원으로 변경: 
 [[1 2 3]
 [4 5 6]]

2. 1차원을 2차원으로 변경: 
 [[1 2]
 [3 4]
 [5 6]]



In [76]:
# 다차원 shape 해석하기 -> 맨 뒤부터 읽어가면서 그림을 그리며 해석하기
arr1D = np.array([1,2,3,4,5,6])
arr1D.shape= (2, 3, 1)
print(arr1D, '\n')
arr1D.shape= (3, 1, 2)
print(arr1D)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 

[[[1 2]]

 [[3 4]]

 [[5 6]]]


#### 2. 속성

In [77]:
arr1 = [[1, 2, 3], [4, 5, 6]]
arr2D = np.array(arr1)
print(vector1, type(vector1), vector1.dtype)

print("1. 2차원 행렬 생성: \n", arr2D, type(arr2D))
print("1. 행렬의 차원(dimension,axis)갯수:", arr2D.ndim)
print("2. 행렬의 각 차원의 크기(shape):", arr2D.shape) # tuple로 반환된다.
print("3. 행렬의 총 요소 갯수(size):", arr2D.size)
print("4. 행렬의 저장 데이터 type(dtype):", arr2D.dtype)

[10 20 30] <class 'numpy.ndarray'> int32
1. 2차원 행렬 생성: 
 [[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
1. 벡터의 차원(dimension,axis)갯수: 2
2. 벡터의 각 차원의 크기(shape): (2, 3)
3. 벡터의 총 요소 갯수(size): 6
4. 벡터의 저장 데이터 type(dtype): int32


#### 3. 랜덤함수로 행렬 생성

In [78]:
# 1) 랜덤값 고정
np.random.seed(1234)

# 2) np.random.random(size=(행,열))
print("1. random(size=(행,열))")
arr = np.random.random()
arr = np.random.random(size=(2, 3))
print(arr, type(arr), arr.dtype)

1. random(size=(행,열))
[[0.62210877 0.43772774 0.78535858]
 [0.77997581 0.27259261 0.27646426]] <class 'numpy.ndarray'> float64


In [81]:
# 3) np.random.rand(행, 열)
# 0 ~ 1의 균등분포에서 표본 추출. 갯수 생략하면  1개반환
print("2. rand(2, 3)")
arr = np.random.rand(2, 3)
print(arr, type(arr), arr.dtype)

2. rand(행, 열)
[[0.71270203 0.37025075 0.56119619]
 [0.50308317 0.01376845 0.77282662]] <class 'numpy.ndarray'> float64


In [82]:
# 3) np.random.randn(행, 열)
# 표준편차가 1이고 평균값이 0인 정규분포에서 표본 추출. 갯수 생략하면  1개반환
print("3. randn(2, 3)")
arr = np.random.randn(2, 3)
print(arr)

3. randn(5)
[[-0.30426018  0.861661   -0.68992667]
 [ 0.18749737  0.60430874 -0.18301422]]


In [83]:
# 4) np.random.randint(low, high, size=(행, 열))
# 주어진 최소/최대 범위 안에서 임의의 난수 n개 추출
print("4. randint(1,10,size=(2, 3))")
arr = np.random.randint(1,10,size=(2, 3))
print(arr)

4. randint(1,10,size=(2, 3))
[[2 4 2]
 [4 8 2]]


In [84]:
# 4) np.random.randint(high, size=(행, 열))
# 0 ~ 최대(exclusive) 범위안에서 임의의 정수 n개 반환, 복원추출
print("4. randint(5, size=(2, 3)): ")
arr = np.random.randint(5, size=(2, 3))
print(arr)

4. randint(5, size=(2, 3)): 
[[4 0 4]
 [1 1 4]]


#### 4. 특정 값으로 행렬 생성

In [87]:
# 1. np.zeros((행, 열))
# shape만큼 0으로 채움. 기본 type은 float64
print("1. np.zeros((2, 3)):")
data = np.zeros((2, 3))
print(data, data.dtype, '\n')
data = np.zeros((2, 3), dtype=np.int32)
print(data, data.dtype)

1. np.zeros((2, 3)):
[[0. 0. 0.]
 [0. 0. 0.]] float64 

[[0 0 0]
 [0 0 0]] int32


In [91]:
# 2. np.ones((행, 열))
# shape만큼  1.0 으로 채움. 기본 type은 float64
print("2. np.ones((2, 3)):")
data = np.ones((2, 3))
print(data , data.dtype)
data = np.ones((2, 3), dtype=np.int32)
print(data, data.dtype)

2. np.ones((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1 1 1]
 [1 1 1]] int32


In [90]:
# 3. np.empty((행, 열))
# shape 만큼 임의의 값으로 채워짐 ==> 임의의 값으로 초기화 시킨 것
print("3. np.empty((2, 3))")
data = np.empty((2, 9))
print(data , data.dtype)
data = np.empty((2, 9), dtype=np.int32)
print(data , data.dtype)

3. np.empty(3)
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.39077217e-307
  1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306
  1.37962320e-306]
 [1.29060871e-306 2.22518251e-306 1.33511969e-306 1.78022342e-306
  1.05700345e-307 3.11525958e-307 8.90092016e-307 1.24611062e-306
  1.42410974e-306]] float64
[[ 1889785610  1068960317  1889785610  1070008893   343597384  1070679982
   1889785610  1071057469  -858993460]
 [ 1071434956   343597384  1071728558 -1030792151  1071917301  1889785610
   1072106045   515396075  1072294789]] int32


In [92]:
# 4. np.full((행, 열), 값)
# shape 만큼 지정된 값으로 채워짐
print("4. full((2, 3), 10)")
data = np.full((2, 3), 10)
print(data)

4. full((2, 3), 10)
[[10 10 10]
 [10 10 10]]


#### 5. arange + reshape 사용하여 행렬 생성

In [93]:
# 1차원 벡터를 reshape를 이용해 2차원 행렬 생성
print("1. arange(10)")
data = np.arange(10).reshape((2, 5))
print(data)

1. arange(10)
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 6. 행렬 삭제
    - arr = np.delete(arr, idx|fancy|slice, axis)
    - axis = None: flatten / axis = 0: 행 제거 / axis = 1: 열 제거

In [94]:
arr2D = np.arange(25).reshape(5,5)
print(arr2D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


##### axis 미지정(None)

In [95]:
# 1. idx 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, -1)
print(xxx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [96]:
# 2. fancy 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, [0,-1])
print(xxx)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [97]:
# 3. slice 이용한 삭제
# 2차원에서 axis 지정하지 않으면 flatten 된다.
xxx = np.delete(arr2D, np.s_[:8])
print(xxx)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


##### axis = 0

In [98]:
# 4. idx + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, -1, axis=0)
print(xxx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [99]:
# 5. fancy + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, [0,-1], axis=0)
print(xxx)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [100]:
# 6. slice + axis=0 이용한 삭제 ==> 행이 삭제됨
xxx = np.delete(arr2D, np.s_[:3], axis=0)
print(xxx)

[[15 16 17 18 19]
 [20 21 22 23 24]]


##### axis = 1

In [101]:
# 7. idx + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, -1, axis=1)
print(xxx)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [102]:
# 8. fancy + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, [0,-1], axis=1)
print(xxx)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]


In [103]:
# 9. slice + axis=1 이용한 삭제 ==> 열이 삭제됨
xxx = np.delete(arr2D, np.s_[:3], axis=1)
print(xxx)

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


#### 7. 행렬 추가 및 삽입
    - 벡터와 차이점은 axis 지정 여부에 따라 출력이 달라진다.

In [108]:
arr = np.array([[1,2,3],[4,5,6]])

# 1. append 함수
# 1) axis=None 지정한 추가
# 2차원에서 axis 지정하지 않으면 flatten 되어 추가됨. 따라서 dimension 일치하지 않아도 된다.
xxx = np.append(arr, [100,200,300,400])
print(xxx, '\n')

# 2) axis=0 지정한 추가 ==> 행 추가
xxx = np.append(arr, [[100,200,300]], axis=0)
print(xxx, '\n')

# 3) axis=1 지정한 추가 ==> 열 추가
xxx = np.append(arr, [[100],[200]], axis=1)
print(xxx)

[  1   2   3   4   5   6 100 200 300 400] 

[[  1   2   3]
 [  4   5   6]
 [100 200 300]] 

[[  1   2   3 100]
 [  4   5   6 200]]


In [109]:
# 2. insert 함수
arr = np.array([[1,2,3],[4,5,6]])

# 1) axis=None 지정한 삽입
# 2차원에서 axis 지정하지 않으면 flatten 되어 추가됨. 따라서 dimension 일치하지 않아도 된다.
xxx = np.insert(arr, 0,  [100,200,300,400])
print(xxx, '\n')

# 2) axis=0 지정한 삽입 ==> 행 삽입
xxx = np.insert(arr, 0,  [[100,200,300]], axis=0)
print(xxx, '\n')

# 3) axis=1 지정한 삽입 ==> 열 삽입
xxx = np.insert(arr, 0, [[100],[200]], axis=1)
print(xxx)

[100 200 300 400   1   2   3   4   5   6] 

[[100 200 300]
 [  1   2   3]
 [  4   5   6]] 

[[100 200   1   2   3]
 [100 200   4   5   6]]


### Type 변환
- 다차원 배열의 모든 요소가 한꺼번에 변경된다.(벡터 연산)
    - dtype 속성 이용
    - astype 함수 이용(많이 사용)

In [110]:
# 1. int32 --> float64으로
data = [10,20,30]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.float64)
arr3 = arr1.astype(np.float64)
print("1. 원본 데이터: ", arr1.dtype , arr1)
print("2. int값을 float으로 변경 1: ", arr2.dtype , arr2)
print("2. int값을 float으로 변경 2: ", arr3.dtype , arr3)

1. 원본 데이터:  int32 [10 20 30]
2. int값을 float으로 변경 1:  float64 [10. 20. 30.]
2. int값을 float으로 변경 2:  float64 [10. 20. 30.]


In [113]:
# 2. float --> int 으로
data = [10.5, 20.7, 30.23, 100]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.int64)
arr3 = arr1.astype(np.int64)
print("3. 원본 데이터: ", arr1.dtype , arr1)
print("4. float 값을 int 으로 변경 1: ", arr2.dtype , arr2)
print("4. float 값을 int 으로 변경 2: ", arr3.dtype , arr3)

3. 원본 데이터:  float64 [ 10.5   20.7   30.23 100.  ]
4. float 값을 int 으로 변경 1:  int64 [ 10  20  30 100]
4. float 값을 int 으로 변경 2:  int64 [ 10  20  30 100]


In [116]:
# 3. int --> bytes , str
data = [10,20,30]
arr1 = np.array(data)
arr2 = np.array(data , dtype=np.string_)  # bytes 타입,  np.string 안됨.
arr3 = arr1.astype(np.string_)
arr4 = np.array(data , dtype=np.str_)   # str 타입 , dtype=np.str 안됨.
arr5 = arr1.astype(np.str_)
print("5. 원본 데이터: ", arr1.dtype , arr1)
print("6. int 값을 bytes 으로 변경 1: ", arr2.dtype , arr2)
print("6. int 값을 bytes 으로 변경 2: ", arr3.dtype , arr3)
print("7. int 값을 str 으로 변경 : ", arr4.dtype , arr4)
print("7. int 값을 str 으로 변경 : ", arr5.dtype , arr5)

# print(dir(np))

5. 원본 데이터:  int32 [10 20 30]
6. int 값을 bytes 으로 변경 1:  |S2 [b'10' b'20' b'30']
6. int 값을 bytes 으로 변경 2:  |S11 [b'10' b'20' b'30']
7. int 값을 str 으로 변경 :  <U2 ['10' '20' '30']
7. int 값을 str 으로 변경 :  <U11 ['10' '20' '30']


In [119]:
# 4. str --> int
data =['10','20','30']
arr1 = np.array(data)
print("원본:", arr1, arr1.dtype)
arr2 = arr1.astype(np.int32)
print("8. str 값을 int 으로 변경 :", arr2, arr2.dtype) # [10 20 30]

arr3 = np.array(data).astype(np.int32)
print(arr3, arr2.dtype) # [10 20 30]

원본: ['10' '20' '30'] <U2
8. str 값을 int 으로 변경 : [10 20 30] int32
[10 20 30] int32


### 벡터 연산

In [120]:
# 1. 기본 파이썬 연산
print("1. 파이썬의 리스트 + 리스트")
print([10,20,30]+[10,20,30])

print("2. 기본 파이썬의 리스트 + 스칼라")
# print([10,20,30] + 2)  # TypeError: can only concatenate list (not "int") to list
print([10,20,30] * 3)

1. 파이썬의 리스트 + 리스트
[10, 20, 30, 10, 20, 30]
2. 기본 파이썬의 리스트 + 스칼라
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [121]:
# 2. 다차원 배열 + 다차원 배열 ==> 요소간 연산, 반드시 shape 일치해야 된다.
arr1D_1 = np.array([10,20,30])
arr1D_2 = np.array([5,4,3])
print("3. numpy의 벡터간 연산 처리")
print(arr1D_1 + arr1D_2)
print(arr1D_1 - arr1D_2)
print(arr1D_1 * arr1D_2)
print(arr1D_1 / arr1D_2)

3. numpy의 벡터간 연산 처리
[15 24 33]
[ 5 16 27]
[50 80 90]
[ 2.  5. 10.]


In [122]:
# 3. 백터 + 스칼라 ==> 자동으로 브로드캐스팅(개수를 맞춰줌) 되어 연산됨.
# 브로드캐스팅(broadcasting): 서로 다른 차원을 가지고 있는 두 개의 값을 산술하는 도중에
# 연산이 가능하도록 차원을 자동으로 맞추어 주는 작업을 의미한다.
arr1D_1 = np.array([10,20,30])
print("4. numpy의 벡터 + 스칼라 연산 처리")
print(arr1D_1 + 2)
print(arr1D_1 - 2)
print(arr1D_1 * 2)
print(arr1D_1 / 2)

4. numpy의 벡터 + 스칼라 연산 처리
[12 22 32]
[ 8 18 28]
[20 40 60]
[ 5. 10. 15.]


In [125]:
# 4. 비교 연산도 벡터화 가능
print("5. 벡터의 비교 연산처리1: ", arr1D_1%3 == 0)
print("5. 벡터의 비교 연산처리2: ", arr1D_1 > 15)
print("5. 벡터의 비교 연산처리3: ", (arr1D_1 > 15) & ( arr1D_1%6 == 0))

5. 벡터의 비교 연산처리1:  [False False  True]
5. 벡터의 비교 연산처리2:  [False  True  True]
5. 벡터의 비교 연산처리3:  [False False  True]


### 색인

#### 1. 1차원 배열(벡터) 색인

In [145]:
arr = np.arange(10)
print("원본:", arr)

# 1. 인덱싱
print("1. 인덱싱:", arr[0], arr[-1])

# 2. 슬라이싱
print("2. 슬라이싱:", arr[1:5], arr[:5], arr[1:], arr[1:10:2], arr[:], arr[...]) # [...]은 numpy에서만 지원

원본: [0 1 2 3 4 5 6 7 8 9]
1. 인덱싱: 0 9
2. 슬라이싱: [1 2 3 4] [0 1 2 3 4] [1 2 3 4 5 6 7 8 9] [1 3 5 7 9] [0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


In [146]:
# 3. fancy 색인
data = np.arange(10) * 100
print("3. original:", data)
# print(data[1, 3, 5]) -> error
print("3-1. fancy data[[1, 3, 5]]:", data[[1, 3, 5]])
print("3-2. fancy data[[8, 1, 5]]:", data[[8, 1, 5]])

3. original: [  0 100 200 300 400 500 600 700 800 900]
3-1. fancy data[[1, 3, 5]]: [100 300 500]
3-2. fancy data[[8, 1, 5]]: [800 100 500]


In [144]:
# 4. boolean 색인 -> True의 결과값을 가진 요소만 나온다, 반드시 색인 대상과 길이가 같아야 함
data = np.array([1,2,3,4,5])
print("4. original: " , data)
print("4-1. 벡터연산,  data%2==0: " , data%2==0)
print("4-2. boolean 색인, [True,True,True,True,False]:",data[[True,True,True,True,False]])
print("4-3. boolean 색인 활용, data[data%2==0]:",data[data%2==0])
print("4-4. boolean 색인 활용, data[data > 3 ]:",data[data > 3])
print("4-5. boolean 색인의 & 연산자:" , data[(data%2==0) & (data >2)]) 
print("4-6. boolean 색인의 | 연산자" , data[(data%2!=0) | (data < 4)])
print("4-7. boolean 색인 활용, data[data > 3 ]:",data[~(data > 3)])

4. original:  [1 2 3 4 5]
4-1. 벡터연산,  data%2==0:  [False  True False  True False]
4-2. boolean 색인, [True,True,True,True,False]: [1 2 3 4]
4-3. boolean 색인 활용, data[data%2==0]: [2 4]
4-4. boolean 색인 활용, data[data > 3 ]: [4 5]
4-5. boolean 색인의 & 연산자: [4]
4-6. boolean 색인의 | 연산자 [1 2 3 5]
4-7. boolean 색인 활용, data[data > 3 ]: [1 2 3]


In [151]:
# 실습: 특정 이름 검색
names = np.array(['홍길동', '세종',"홍길동","이순신","정조","홍길동"])

# 홍길동
print(names[names=='홍길동'])
print([i for i in names if i=='홍길동'])

['홍길동' '홍길동' '홍길동']
['홍길동', '홍길동', '홍길동']


## 6/12(월)

In [2]:
import numpy as np

### 색인

#### 2차원 색인
- 기본적으로 arr[행, 열] 형식을 따른다.

In [3]:
# 1) 인덱싱 및 슬라이싱
arr = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])
print("1. original: ", arr)  
print("2. 1행만 반환1",    arr[0]) 
print("2. 1행만 반환2",    arr[0,...])  
print("3. 마지막 행만 반환",    arr[-1])  

print("3. 1행의 1열 반환 " , arr[0,1])  
print("4. 1행의 마지막 열 반환 " ,arr[0, -1]) 
print("5. 1행의 2열이후 반환 " ,arr[0, 1:]) 

print("6. 1열만 반환1 " , arr[:, 0])  
print("6. 1열만 반환2 " , arr[..., 0]) 
print("7. 2열이후 반환 " , arr[:, 1:]) 

print("8. 2행이후 2열이후 반환 " , arr[1:, 1:]) 

1. original:  [[   1    2    3]
 [  10   20   30]
 [ 100  200  300]
 [1000 2000 3000]]
2. 1행만 반환1 [1 2 3]
2. 1행만 반환2 [1 2 3]
3. 마지막 행만 반환 [1000 2000 3000]
3. 1행의 1열 반환  2
4. 1행의 마지막 열 반환  3
5. 1행의 2열이후 반환  [2 3]
6. 1열만 반환1  [   1   10  100 1000]
6. 1열만 반환2  [   1   10  100 1000]
7. 2열이후 반환  [[   2    3]
 [  20   30]
 [ 200  300]
 [2000 3000]]
8. 2행이후 2열이후 반환  [[  20   30]
 [ 200  300]
 [2000 3000]]


In [4]:
# 2) fancy 색인
arr = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("1. original: ", arr) 
print("2. 1행과 3행만 반환", arr[[0, 2]])  

print("3. 1행과 3행에서 2열만 반환: ", arr[[0, 2], [1]]) 
print("4. 1행과 3행에서 2열 이후 반환", arr[[0, 2], 1:])  
print("5. 2열과 3열만 반환", arr[:, [1, 2]])

1. original:  [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
2. 1행과 3행만 반환 [[  1   2   3]
 [100 200 300]]
3. 1행과 3행에서 2열만 반환:  [  2 200]
4. 1행과 3행에서 2열 이후 반환 [[  2   3]
 [200 300]]
5. 2열과 3열만 반환 [[  2   3]
 [ 20  30]
 [200 300]]


In [5]:
# 3) boolean 색인
arr = np.array([[1,2,3],[10,20,30],[100,200,300]])
print("1. original: ", arr) 
print("2. arr%2==0: ", arr%2==0) 
print("3. arr[arr%2==0]: ", arr[arr%2==0])  
print("4. arr[(arr%2!=0) | (arr < 100)] " , arr[(arr%2!=0) | (arr < 100)])

1. original:  [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
2. arr%2==0:  [[False  True False]
 [ True  True  True]
 [ True  True  True]]
3. arr[arr%2==0]:  [  2  10  20  30 100 200 300]
4. arr[(arr%2!=0) | (arr < 100)]  [ 1  2  3 10 20 30]


#### 색인을 이용한 값 변경

In [9]:
arr = np.arange(10)
print('0. original:', arr)

# 1) indexing을 이용한 값 변경
arr[0] = 100
print('1. indexing:', arr)

# 2) slicing
arr[1:4] = 200
print('2. slicing:', arr)

# 3) fancy 색인
arr[[-1, -2, -3]] = 50
print('3. fancy:', arr)

# 4) boolean 색인
arr[arr>=100] = 0
print('4. boolean:', arr)

# 5) 모든 값을 1로 변경
arr[:] = 1
print('5. 모든 값 1 변경:', arr)

0. original: [0 1 2 3 4 5 6 7 8 9]
1. indexing: [100   1   2   3   4   5   6   7   8   9]
2. slicing: [100 200 200 200   4   5   6   7   8   9]
3. fancy: [100 200 200 200   4   5   6  50  50  50]
4. boolean: [ 0  0  0  0  4  5  6 50 50 50]
5. 모든 값 1 변경: [1 1 1 1 1 1 1 1 1 1]


#### 얕은 복사, 깊은 복사

In [11]:
# 1) Python 얕은 복사
x = [1, 2, 3]
x2 = x
print(id(x), id(x2))

x2[0] = 100
print(x, x2)

2533216421056 2533216421056
[100, 2, 3] [100, 2, 3]


In [14]:
# 2) Python 깊은 복사
x = [1, 2, 3]
x3 = x[:]
x3 = x.copy()
x3 = list(x)
print(id(x), id(x3))

x3[1] = 100
print(x, x3)

2533216193920 2533216433536
[1, 2, 3] [1, 100, 3]


In [16]:
# 3) Numpy 얕은 복사
arr = np.array([1, 2, 3])
print(arr)

arr2 = arr[:]
print(id(arr), id(arr2))

arr2[0] = 100
print(arr, arr2)

[1 2 3]
2532837217104 2532837213264
[100   2   3] [100   2   3]


In [18]:
# 4) Numpy 깊은 복사
arr = np.array([1, 2, 3])
arr3 = np.copy(arr)
print(id(arr), id(arr3))

arr3[0] = 100
print(arr, arr3)

2532837212592 2532836818736
[1 2 3] [100   2   3]


#### 병합

In [23]:
# 열 병합
arr = np.arange(9).reshape(3,3)
arr2 = arr * 2
column_merge = np.hstack((arr,arr2))
column_merge2 = np.concatenate((arr,arr2) , axis=1)
column_merge3= np.column_stack((arr, arr2))
print('0. original:', arr, arr2, sep='\n')

print('1. np.hstack:', column_merge, sep='\n')
print('2. np.concatenate(axis=1):', column_merge2, sep='\n')
print('3. np.column_stack:', column_merge3, sep='\n')

0. original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
1. np.hstack:
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
2. np.hstack:
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
3. np.hstack:
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [24]:
# 행 병합
arr = np.arange(9).reshape(3,3)
arr2 = arr * 2
row_merge = np.vstack((arr,arr2))
row_merge2 = np.concatenate((arr,arr2) , axis=0)
row_merge3= np.row_stack((arr, arr2))
print("1. vstack(튜플): \n",row_merge)
print("2. concatenate(튜플, axis=0): \n",row_merge2)
print("3. row_stack(튜플): \n",row_merge3)

1. vstack(튜플): 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
2. concatenate(튜플, axis=0): 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
3. row_stack(튜플): 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


#### 분할

In [28]:
arr = np.arange(12).reshape(3, 4)

# 1. 열 분할
column_split, column_split2 = np.hsplit(arr, 2)
print("1. column_split: \n", column_split)
print("1. column_split2: \n", column_split2)

column_split, column_split2 = np.split(arr, 2, axis=1)
print("2. column_split: \n", column_split)
print("2. column_split2: \n", column_split2)

1. column_split: 
 [[0 1]
 [4 5]
 [8 9]]
1. column_split2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]
2. column_split: 
 [[0 1]
 [4 5]
 [8 9]]
2. column_split2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [31]:
arr = np.arange(12).reshape(3, 4)
# 2. 행분할
row_split,row_split2, row_split3 = np.vsplit(arr, 3)
print("1. vsplit(arr,3): ", row_split, row_split2, row_split3)

row_split,row_split2, row_split3 = np.split(arr, 3, axis=0)
print("2. vsplit(arr,3): ", row_split, row_split2, row_split3)

1. vsplit(arr,3):  [[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]
2. vsplit(arr,3):  [[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]


#### 함수

##### 범용 함수(universal function)

###### 단항 유니버셜 함수

In [37]:
# 1. np.abs: 절대값
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("1. original: " , arr)
print("2. np.abs(arr): " , np.abs(arr))

# 2. np.around: 0.5를 기준으로 올림 혹은 내림 -> 0.5까지 내림, 그 이상은 올림
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("3. original: " , arr)
print("4. np.around(arr): " , np.around(arr))

# 3. np.round: N 소수점 자릿수까지 반올림
arr = np.array([-4.62985, -2.19568, 0, 1.5754, 3.4056, 4.06898])
print("5. original: " , arr)
print("6. np.round(arr, 1): " , np.round(arr, 1))
print("6. np.round(arr, 3): " , np.round(arr, 3))

1. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
2. np.abs(arr):  [4.62 2.19 0.   1.57 3.4  4.06]
3. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
4. np.around(arr):  [-5. -2.  0.  2.  3.  4.]
5. original:  [-4.62985 -2.19568  0.       1.5754   3.4056   4.06898]
6. np.round(arr, 1):  [-4.6 -2.2  0.   1.6  3.4  4.1]
6. np.round(arr, 3):  [-4.63  -2.196  0.     1.575  3.406  4.069]


In [33]:
# 4. np.rint: 가장 가까운 정수로 올림 혹은 내림
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("7. original: ", arr)
print("8. np.rint(arr): ", np.rint(arr))

# 5. np.fix: 0 방향으로 가장 가까운 정수로 올림 혹은 내림
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("9. original: ", arr)
print("10. np.fix(arr): ", np.fix(arr))

# 6. np.ceil: 각 원소보다 크거나 같은 가장 작은 정수값으로 올림
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("11. original: " , arr)
print("12. np.ceil(arr): " , np.ceil(arr))

7. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
8. np.rint(arr):  [-5. -2.  0.  2.  3.  4.]
9. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
10. np.fix(arr):  [-4. -2.  0.  1.  3.  4.]
11. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
12. np.ceil(arr):  [-4. -2.  0.  2.  4.  5.]


In [34]:
# 7. np.floor: 각 원소보다 작거나 같은 가장 큰 정수값으로 내림
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("13. original: " , arr)
print("14. np.floor(arr): " , np.floor(arr))

# 8. np.trunc: 각 원소의 소수점 부분은 잘라버리고 정수값만 남김
arr = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
print("15. original: " , arr)
print("16. np.trunc(arr): " , np.trunc(arr))

# 9. np.sqrt: 제곱근
arr = np.array([1,4,9,16,25])
print("17. original: " ,arr)
print("18. np.sqrt(arr): " , np.sqrt(arr))

# 10. np.reciprocal : 각 요소의 역수
print("19. np.reciprocal 1: ", np.reciprocal([1,2,3]))
print("20. np.reciprocal 2: ", np.reciprocal([1.,2.,3.]))

13. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
14. np.floor(arr):  [-5. -3.  0.  1.  3.  4.]
15. original:  [-4.62 -2.19  0.    1.57  3.4   4.06]
16. np.trunc(arr):  [-4. -2.  0.  1.  3.  4.]
17. original:  [ 1  4  9 16 25]
18. np.sqrt(arr):  [1. 2. 3. 4. 5.]
19. np.reciprocal 1:  [1 0 0]
20. np.reciprocal 2:  [1.         0.5        0.33333333]


---

In [67]:
# 1. np.sum: 1차원 배열 원소간 합
b = np.array([1, 2, 3, 4])
#print("average:" , np.average(b))
print("1. original: " , b ) # [1 2 3 4]
print("2. np.sum: " , np.sum(b) ) # 1+2+3+4 = 10                        , 스칼라 값으로 배월 원소 간 합을 반환
print("3. np.sum(keepdims=True): " , np.sum(b , keepdims=True) ) # [10] , 1차원 배열로 배열 원소 간 합을 반환

# 2. np.sum: 2차원 배열 원소간 합
c = np.array([[1, 2], [3, 4],[5,6]])
print("4. original: " , c )
print("5. np.sum(axis=0): " , np.sum(c , axis=0) ) # [ 9 12]    위 + 아래  ( axis=0 인 행축 기준 )
print("6. np.sum(axis=1): " , np.sum(c , axis=1) ) # [ 3  7 11] 왼쪽 + 오른쪽 ( axis=1인 열축 기준 )

1. original:  [1 2 3 4]
2. np.sum:  10
3. np.sum(keepdims=True):  [10]
4. original:  [[1 2]
 [3 4]
 [5 6]]
5. np.sum(axis=0):  [ 9 12]
6. np.sum(axis=1):  [ 3  7 11]


In [69]:
# 3. np.nansum: NaN 을 0로 간주하고 배열 원소 간 합처리
c = np.array([[1, 2], [3, np.nan]])
print("7. original: " , c )
print("8. np.sum(axis=0): " , np.sum(c , axis=0) ) # [ 4. nan]       위 + 아래
print("9. np.sum(axis=1): " , np.sum(c , axis=1) ) # [ 3. nan]       왼쪽 + 오른쪽
print("10. np.nansum(axis=0): " , np.nansum(c , axis=0) ) # [4. 2.]  위 + 아래
print("11. np.nansum(axis=1): " , np.nansum(c , axis=1) ) # [3. 3.]  왼쪽 + 오른쪽

# 4. np.cumsum: 배열 원소간 누적 합하기(중요)
c = np.array([[1, 2], [3, 4],[5,6]])
print("12. original: " , c )
print("13. np.cumsum(axis=0): ", np.cumsum(c, axis=0) ) # [[ 1 2][1+3 2+4][1+3+5 2+4+6]]
print("14. np.cumsum(axis=1): ", np.cumsum(c, axis=1) ) # [[ 1 1+2][3 3+4][5 5+6]]

# 5. np.mean ==> 평균 (sql -> avg / python - 제공 안 됨)
print("9.  1차원 배열 np.mean(arr) : ", np.mean([1, 2, 3, 4]))  # 2.5
print("10. 2차원 배열 np.mean(arr, axis=0): ",
      np.mean([[1, 2, 3, 4],[1, 2, 3, 4]], axis=0))  # [1. 2. 3. 4.]
print("11. 2차원 배열 np.mean(arr, axis=1):",
      np.mean([[1, 2, 3, 4],[1, 2, 3, 4]], axis=1))  # [2.5 2.5]

7. original:  [[ 1.  2.]
 [ 3. nan]]
8. np.sum(axis=0):  [ 4. nan]
9. np.sum(axis=1):  [ 3. nan]
10. np.nansum(axis=0):  [4. 2.]
11. np.nansum(axis=1):  [3. 3.]
12. original:  [[1 2]
 [3 4]
 [5 6]]
13. np.cumsum(axis=0):  [[ 1  2]
 [ 4  6]
 [ 9 12]]
14. np.cumsum(axis=1):  [[ 1  3]
 [ 3  7]
 [ 5 11]]
9.  1차원 배열 np.mean(arr) :  2.5
10. 2차원 배열 np.mean(arr, axis=0):  [1. 2. 3. 4.]
11. 2차원 배열 np.mean(arr, axis=1): [2.5 2.5]


In [73]:
# 6. np.median ==> 중앙값 (내부적으로 정렬하고 가운데 있는 값을 반환)
arr = np.array([6, 8, 3, 5, 1])
print("[6. 8. 3. 5. 1]의 중앙값:", np.median(arr))
arr2 = np.array([6, 8, 3, 5, 1, 9])
print("[6, 8, 3, 5, 1, 9]의 중앙값:", arr2)

# 7. np.var ==> 분산 ( 관측값에서 평균을 뺀값을 제곱하고 모두 더해서 갯수로 나눈다. 즉, 차이값(잔차)의 제곱의 평균이다.
print("12. 1차원 배열 np.var(arr): ", np.var([1, 20, 3, 40]))  # 246.5
print("13. 2차원 배열 np.var(arr, axis=0): ",
      np.var([[1, 20, 3, 40],[4, 6, 7, 80]], axis=0))  # [  2.25  49.     4.   400.
print("14. 2차원 배열 np.var(arr, axis=1): ",
      np.var([[1, 20, 3, 40],[4, 6, 7, 80]], axis=1))  # [ 246.5    1037.1875]

# 8. np.std ==> 표준 편차 ( 분산을 제곱근한 것이다. 제곱해서 값이 부풀려진 것을 다시 원래대로 복원)
print("15. 1차원 배열 np.std(arr): ", np.std([1, 20, 3, 40]), np.sqrt(np.var([1, 20, 3, 40])))  # 15.700318468107582
print("16. 2차원 배열 np.std(arr, axis=0): ",
      np.std([[1, 20, 3, 40],[4, 6, 7, 80]], axis=0))  # [ 1.5  7.   2.  20. ]
print("17. 2차원 배열 np.std(arr, axis=1): ",
      np.std([[1, 20, 3, 40],[4, 6, 7, 80]], axis=1))  # [15.70031847 32.20539551]

[6. 8. 3. 5. 1]의 중앙값: 5.0
[6, 8, 3, 5, 1, 9]의 중앙값: [6 8 3 5 1 9]
12. 1차원 배열 np.var(arr):  246.5
13. 2차원 배열 np.var(arr, axis=0):  [  2.25  49.     4.   400.  ]
14. 2차원 배열 np.var(arr, axis=1):  [ 246.5    1037.1875]
15. 1차원 배열 np.std(arr):  15.700318468107582 15.700318468107582
16. 2차원 배열 np.std(arr, axis=0):  [ 1.5  7.   2.  20. ]
17. 2차원 배열 np.std(arr, axis=1):  [15.70031847 32.20539551]


###### 이항 유니버셜 함수

In [42]:
# 1. np.add:  + 연산과 동일
b = np.array([1, 2, 3, 4])
print("1. original: " , b )
print("2. b+b: " , b+b )
print("3. np.add(b,b): " , np.add(b,b) )
print('-'*100)
# 2. np.subtract:  - 연산과 동일
b = np.array([1, 2, 3, 4])
print("1. original: " , b )
print("2. b*2-b: " , b*2-b )
print("3. np.subtract(b*2,b): " , np.subtract(b*2,b) )
print('-'*100)
# 3. np.multiply:  * 연산과 동일
b = np.array([1, 2, 3, 4])
print("1. original: " , b )
print("2. b*b: " , b*b )
print("3. np.multiply(b,b): " , np.multiply(b,b) )
print('-'*100)
# 4. np.divide:  / 연산과 동일
b = np.array([1, 2, 3, 4])
print("1. original: " , b )
print("2. b/b: " , b/b )
print("3. np.divide(b,b): " , np.divide(b,b) )

1. original:  [1 2 3 4]
2. b+b:  [2 4 6 8]
3. np.add(b,b):  [2 4 6 8]
----------------------------------------------------------------------------------------------------
1. original:  [1 2 3 4]
2. b*2-b:  [1 2 3 4]
3. np.subtract(b*2,b):  [1 2 3 4]
----------------------------------------------------------------------------------------------------
1. original:  [1 2 3 4]
2. b*b:  [ 1  4  9 16]
3. np.multiply(b,b):  [ 1  4  9 16]
----------------------------------------------------------------------------------------------------
1. original:  [1 2 3 4]
2. b/b:  [1. 1. 1. 1.]
3. np.divide(b,b):  [1. 1. 1. 1.]


In [43]:
# 5. np.floor_divide:  // 연산과 동일 ( 몫 연산 )
b = np.array([5,6,7,8])
b2 = np.array([3,3,3,3])
print("1. original: " , b ) # [5 6 7 8]
print("2. b//b2: " , b//b2 ) # [1 2 2 2]
print("3. np.floor_divide(b,b): " , np.floor_divide(b,b2) ) # [1 2 2 2]
print('-'*100)
# 6. np.mod:  % 연산과 동일 ( 나머지 연산 )
b = np.array([5,6,7,8])
b2 = np.array([3,3,3,3])
print("1. original: " , b ) # [5 6 7 8]
print("2. b%b2: " , b%b2 ) # [2 0 1 2]
print("3. np.mod(b,b2): " , np.mod(b,b2) ) # [2 0 1 2]
print("4. np.remainder(b,b2): " , np.remainder(b,b2) ) # [2 0 1 2]

1. original:  [5 6 7 8]
2. b//b2:  [1 2 2 2]
3. np.floor_divide(b,b):  [1 2 2 2]
----------------------------------------------------------------------------------------------------
1. original:  [5 6 7 8]
2. b%b2:  [2 0 1 2]
3. np.mod(b,b2):  [2 0 1 2]
4. np.remainder(b,b2):  [2 0 1 2]


In [44]:
# 7. np.maximum  인덱스별로 큰 값 반환
b = np.array([5,6,7,8])
b2 = np.array([1,9,6,8])
print("1. original: " , b ) # [5 6 7 8]
print("2. np.maximum(b,b2): " , np.maximum(b,b2) ) # [5 9 7 8]
print("3. np.minimum(b,b2): " , np.minimum(b,b2) ) #  [1 6 6 8]
print("4. np.greater(b,b2): " , np.greater(b,b2) ) #  [ True False  True False]
print("5. np.greater_equal(b,b2): " , np.greater_equal(b,b2) ) #  [ True False  True  True]
print("6. np.less(b,b2): " , np.less(b,b2) ) #  [False  True False False]
print("7. np.less_equal(b,b2): " , np.less_equal(b,b2) ) #  [False  True False  True]
print("8. np.equal(b,b2): " , np.equal(b,b2) ) #  [False False False  True]
print("9. np.not_equal(b,b2): " , np.not_equal(b,b2) ) #  [ True  True  True False]
print('-'*100)
# 8. np.power : 제곱
print("1. np.power:" , np.power(2, 3))  # 8

1. original:  [5 6 7 8]
2. np.maximum(b,b2):  [5 9 7 8]
3. np.minimum(b,b2):  [1 6 6 8]
4. np.greater(b,b2):  [ True False  True False]
5. np.greater_equal(b,b2):  [ True False  True  True]
6. np.less(b,b2):  [False  True False False]
7. np.less_equal(b,b2):  [False  True False  True]
8. np.equal(b,b2):  [False False False  True]
9. np.not_equal(b,b2):  [ True  True  True False]
----------------------------------------------------------------------------------------------------
1. np.power: 8


###### 문자열 유니버셜 함수
https://numpy.org/devdocs/reference/routines.char.html#module-numpy.char

In [61]:
# 1. np.char.add
x1 = np.array(['Hello', 'Say'], dtype=str)
x2 = np.array([' world', ' something'], dtype=str)
out = np.char.add(x1, x2)
print("1. np.char.add(x1,x2):", out) # ['Hello world' 'Say something']

# 2. np.char.multiply
x = np.array(['Hello ', 'Say '], dtype=str)
out = np.char.multiply(x, 3)
print("2. np.char.multiply(x, 3):", out) # ['Hello Hello Hello ' 'Say Say Say ']

# 2. np.char.함수
x = np.array(['heLLo woRLd', 'Say sOmething'], dtype=str)
capitalized = np.char.capitalize(x)
# python
# print('heLLo woRLd'.lower())
# print('heLLo woRLd'.upper())
# print('heLLo woRLd'.swapcase())
lowered = np.char.lower(x)
uppered = np.char.upper(x)
swapcased = np.char.swapcase(x)
titlecased = np.char.title(x)
print("3. capitalized =", capitalized) # ['Hello world' 'Say something']
print("4. lowered =", lowered) # ['hello world' 'say something']
print("5. uppered =", uppered) #  ['HELLO WORLD' 'SAY SOMETHING']
print("6. swapcased =", swapcased) # ['HEllO WOrlD' 'sAY SoMETHING']
print("7. titlecased =", titlecased) # ['Hello World' 'Say Something']

1. np.char.add(x1,x2): ['Hello world' 'Say something']
2. np.char.multiply(x, 3): ['Hello Hello Hello ' 'Say Say Say ']
3. capitalized = ['Hello world' 'Say something']
4. lowered = ['hello world' 'say something']
5. uppered = ['HELLO WORLD' 'SAY SOMETHING']
6. swapcased = ['HEllO WOrlD' 'sAY SoMETHING']
7. titlecased = ['Hello World' 'Say Something']


In [48]:
# 3. np.char.center,  np.char.ljust, np.char.rjust
x = np.array(['hello world', 'say something'], dtype=str)
centered = np.char.center(x, 20, fillchar='_')
left = np.char.ljust(x, 20, fillchar='_')
right = np.char.rjust(x, 20, fillchar='_')

print("8. centered =", centered) # ['____hello world_____' '___say something____']
print("9. left =", left)       # ['hello world_________' 'say something_______']
print("10. right =", right)    # ['_________hello world' '_______say something']

# 4. np.char.encode,  np.char.decode
x = np.array(['hello world', 'say something'], dtype=str)
encoded = np.char.encode(x, 'cp500')
decoded = np.char.decode(encoded,'cp500')
print("11. encoded =", encoded) # b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
print("12. decoded =", decoded) # ['hello world' 'say something']



8. centered = ['____hello world_____' '___say something____']
9. left = ['hello world_________' 'say something_______']
10. right = ['_________hello world' '_______say something']
11. encoded = [b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'
 b'\xa2\x81\xa8@\xa2\x96\x94\x85\xa3\x88\x89\x95\x87']
12. decoded = ['hello world' 'say something']


In [62]:
# 5. np.char.join
x = np.array(['hello world', 'say something'], dtype=str)
# python
# print(','.join(['A', 'B']))
out = np.char.join(",", x)
print("13. join =", out)  # ['h,e,l,l,o, ,w,o,r,l,d' 's,a,y, ,s,o,m,e,t,h,i,n,g']

x = np.array("hello", dtype=str)
out = np.char.join(",", x)
print("13. join =", out) # h,e,l,l,o

x = np.array([1,2,3], dtype=str)
out = np.char.join(",", x)
print("13. join =", out) # ['1' '2' '3']

# 5. np.char.strip => 기본은 공백제거
x = np.array(['   hello world   ', '\tsay something\n'], dtype=str)
stripped = np.char.strip(x)
lstripped = np.char.lstrip(x)
rstripped = np.char.rstrip(x)
print("14. stripped =", stripped) # ['hello world' 'say something']
print("15. lstripped =", lstripped) # ['hello world   ' 'say something\n']
print("16. rstripped =", rstripped) # ['   hello world' '\tsay something']

x =np.array(['aAaAaA', '  aA  ', 'abBABba'])
print("16. ", np.char.strip(x, 'a')) # ['AaAaA' '  aA  ' 'bBABb']
print("16. ", np.char.lstrip(x, 'a')) # ['AaAaA' '  aA  ' 'bBABba']
print("16. ", np.char.rstrip(x, 'a')) # ['aAaAaA' '  aA  ' 'abBABb']

13. join = ['h,e,l,l,o, ,w,o,r,l,d' 's,a,y, ,s,o,m,e,t,h,i,n,g']
13. join = h,e,l,l,o
13. join = ['1' '2' '3']
14. stripped = ['hello world' 'say something']
15. lstripped = ['hello world   ' 'say something\n']
16. rstripped = ['   hello world' '\tsay something']
16.  ['AaAaA' '  aA  ' 'bBABb']
16.  ['AaAaA' '  aA  ' 'bBABba']
16.  ['aAaAaA' '  aA  ' 'abBABb']


In [54]:
# 6. np.char.split ==> 기본은 공백으로 분리
x = np.array(['Hello my name is John'], dtype=str)
out = np.char.split(x)
print("17. split =", out, out[0]) # [list(['Hello', 'my', 'name', 'is', 'John'])] Hello

x = np.array(['He/llo/m/ynameisJ/ohn'], dtype=str)
out = np.char.split(x, '/')
print("17. split =", out, out[0])

# 7. np.char.replace ==> 기본적으로 모두 변경됨. count지정하여 변경갯수 설정가능
x = np.array(['John Hello my name is John'], dtype=str)
out = np.char.replace(x, "John", "Jim", count=1)
print("18. replace =", out) # ['Hello my name is Jim']
print()

# 8. np.char.find
x = np.array(['hello world', 'say something'], dtype=str)
out = np.char.find(x, 'e')  # 'e' 문자의 인덱스 값 반환
print("19. find =", out) # [1 7]

# 9. np.char.count
x = np.array(['Hello', 'my', 'name', 'is', 'Lily'], dtype=str)
out = np.char.count(x, "l")
print("20. count =", out) # [2 0 0 0 1]

17. split = [list(['Hello', 'my', 'name', 'is', 'John'])] ['Hello', 'my', 'name', 'is', 'John']
17. split = [list(['He', 'llo', 'm', 'ynameisJ', 'ohn'])] ['He', 'llo', 'm', 'ynameisJ', 'ohn']
18. replace = ['Jim Hello my name is John']

19. find = [1 7]
20. count = [2 0 0 0 1]


In [55]:
# 10. np.char.startswith
x = np.array(['he', 'his', 'him', 'his'], dtype=str)
out = np.char.startswith(x, "hi")
print("21. startswith =", out) # [False  True  True  True]

# 11. np.char.endswith
x = np.array(['he', 'his', 'him', 'his'], dtype=str)
out = np.char.endswith(x, "s")
print("22. endswith =", out) # [False  True False  True]

# 12. np.char.equal , np.char.not_equal
x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=str)
out = np.char.equal(x1, x2)
print(out)  # [ True  True  True  True False]

x1 = np.array(['Hello', 'my', 'name', 'is', 'John'], dtype=str)
x2 = np.array(['Hello', 'my', 'name', 'is', 'Jim'], dtype=str)
out = np.char.not_equal(x1, x2)
print(out)  # [False False False False  True]

#  13. isdigit, islower, isupper
x = np.array(['Hello', 'I', 'am', '20', 'years', 'old'], dtype=np.str_)
out1 = np.char.isdigit(x)
out2 = np.char.islower(x)
out3 = np.char.isupper(x)
out4 = np.char.isalpha(x)
print("Digits only =", out1) # [False False False  True False False]
print("Lower cases only =", out2)  # [False False  True False  True  True]
print("Upper cases only =", out3)  # [False  True False False False False]
print("Alpha cases only =", out4) # [ True  True  True False  True  True]

21. startswith = [False  True  True  True]
22. endswith = [False  True False  True]
[ True  True  True  True False]
[False False False False  True]
Digits only = [False False False  True False False]
Lower cases only = [False False  True False  True  True]
Upper cases only = [False  True False False False False]
Alpha cases only = [ True  True  True False  True  True]


##### 유틸리티 함수

In [66]:
# 1. np.prod: 1차원 배열 원소간 곱계산인 product
b = np.array([1, 2, 3, 4])
print("1. original: " , b ) # [1 2 3 4]
print("2. np.prod(arr): " , np.prod(b) ) # 1*2*3*4 = 24

# 2. np.prod: 2차원 배열 원소간 곱계산인 product
c = np.array([[1, 2], [3, 4],[5,6]])
print("3. original:\n" , c )
print("4. np.prod(axis=0): " , np.prod(c , axis=0) ) # [15 48]    위 * 아래 ( axis=0 인 행축 기준 )
print("5. np.prod(axis=1): " , np.prod(c , axis=1) ) # [ 2 12 30] 왼쪽 * 오른쪽 ( axis=1인 열축 기준 )

1. original:  [1 2 3 4]
2. np.prod(arr):  24
3. original:
 [[1 2]
 [3 4]
 [5 6]]
4. np.prod(axis=0):  [15 48]
5. np.prod(axis=1):  [ 2 12 30]


In [65]:
# 3. np.nanprod: NaN 을 1로 간주하고 배열 원소 간 곱처리
c = np.array([[1, 2], [3, np.nan]])
print("6.original: " , c )
print("7. np.prod(axis=0): " , np.prod(c , axis=0) ) # [ 3. nan]      위 * 아래 ( axis=0 인 행축 기준 )
print("8. np.prod(axis=1): " , np.prod(c , axis=1) ) # [ 2. nan]      왼쪽 * 오른쪽 ( axis=1인 열축 기준 )
print("9. np.nanprod(axis=0): " , np.nanprod(c , axis=0) ) # [3. 2.]  위 * 아래
print("10. np.nanprod(axis=1): " , np.nanprod(c , axis=1) ) # [2. 3.] 왼쪽 * 오른쪽

# 4. np.cumprod: 배열 원소간 누적 곱하기
c = np.array([[1, 2], [3, 4],[5,6]])
print("11. original: " , c )
print("12. np.cumprod(axis=0): ", np.cumprod(c, axis=0)) # [[ 1 2][ 1*3 2*4] [1*3*5 2*4*6]]
print("13. np.cumprod(axis=1): ", np.cumprod(c, axis=1)) # [[ 1 1*2] [3 3*4] [5 5*6]]

6.original:  [[ 1.  2.]
 [ 3. nan]]
7. np.prod(axis=0):  [ 3. nan]
8. np.prod(axis=1):  [ 2. nan]
9. np.nanprod(axis=0):  [3. 2.]
10. np.nanprod(axis=1):  [2. 3.]
11. original:  [[1 2]
 [3 4]
 [5 6]]
12. np.cumprod(axis=0):  [[ 1  2]
 [ 3  8]
 [15 48]]
13. np.cumprod(axis=1):  [[ 1  2]
 [ 3 12]
 [ 5 30]]


In [76]:
# 5. 최대/최소값
data = np.array([8,2,4,5,10,1])
print("1. 1차원 배열 np.max(arr): " , np.max(data))
print("2. 1차원 배열 np.min(arr): " , np.min(data))

data = np.array(np.arange(16).reshape(4,4))
print(data)
print("3. 2차원 배열, 각 열에서 최대값:" , np.max(data,  axis=0)) # [12 13 14 15]
print("4. 2차원 배열, 각 열에서 최소값:" , np.min(data,  axis=0 )) # [0 1 2 3]
print("5. 2차원 배열, 각 행에서 최대값:" , np.max(data,  axis=1)) # [ 3  7 11 15]
print("6. 2차원 배열, 각 행에서 최소값:" , np.min(data,  axis=1 )) # [ 0  4  8 12]

# 6.  최대/최소값에 해당하는 인덱스 반환
data = np.array([8,2,4,5,10,1])
print("1. 1차원 배열 최대 index값: " , np.max(data), np.argmax(data)) # 10 4
print("2. 1차원 배열 최소 index값: " , np.min(data), np.argmin(data)) # 1  5

data = np.array([[6,2,4],[10,1,54],[66,3,21]])
print(data)
print("3. 2차원 배열, 각 열에서 최대 index값:" , np.argmax(data,  axis=0)) # [2 2 1]
print("4. 2차원 배열, 각 열에서 최소 index값:" , np.argmin(data,  axis=0 )) # [0 1 0]
print("5. 2차원 배열, 각 행에서 최대 index값:" , np.argmax(data,  axis=1)) # [0 2 0]
print("6. 2차원 배열, 각 행에서 최소 index값:" , np.argmin(data,  axis=1 )) # [1 1 1]

1. 1차원 배열 np.max(arr):  10
2. 1차원 배열 np.min(arr):  1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
3. 2차원 배열, 각 열에서 최대값: [12 13 14 15]
4. 2차원 배열, 각 열에서 최소값: [0 1 2 3]
5. 2차원 배열, 각 행에서 최대값: [ 3  7 11 15]
6. 2차원 배열, 각 행에서 최소값: [ 0  4  8 12]
1. 1차원 배열 최대 index값:  10 4
2. 1차원 배열 최소 index값:  1 5
[[ 6  2  4]
 [10  1 54]
 [66  3 21]]
3. 2차원 배열, 각 열에서 최대 index값: [2 2 1]
4. 2차원 배열, 각 열에서 최소 index값: [0 1 0]
5. 2차원 배열, 각 행에서 최대 index값: [0 2 0]
6. 2차원 배열, 각 행에서 최소 index값: [1 1 1]


In [77]:
# Python에서의 정렬
# 1. sorted(값)
#  - __builtins__객체의 함수
#  - 정렬된 복사본 반환
    
# 2. 객체.sort(reverse=True)
#  - 객체의 함수
#  - 자신이 정렬

# 7.  1차원 정렬 - 내림차순으로 반환해주는 파라미터가 없음

data = np.array([8,2,4,5,10,1])
print("1. 1차원 배열 sort 전: ",data) # [ 8  2  4  5 10  1]
print("2. 1차원 배열 sort 후(오름차순): ",np.sort(data)) # [ 1  2  4  5  8 10]
print("3. 1차원 배열 sort 후(내림차순): ",np.sort(data)[::-1]) # [10  8  5  4  2  1]
print()

# 8. 2차원 정렬
data = np.array([[8,2,4,5,10,1],[100,67,33,77,66,90]])

data3 = np.sort(data, axis=None) # flattened
print("6. axis=None(flattened):", data3) # [  1   2   4   5   8  10  33  66  67  77  90 100]
print()
arr = np.array([[8,2,4],[100,67,33],[99,44,77]])
# [[  8   2   4]
#  [100  67  33]
#  [ 99  44  77]]
data4 = np.sort(arr, axis=0) # 컬럼단위로 정렬
print(data4)
# [[  8   2   4]
#  [ 99  44  33]
#  [100  67  77]]
data4 = np.sort(arr, axis=1)  # 행단위로 정렬
print(data4)
# [[  2   4   8]
#  [ 33  67 100]
#  [ 44  77  99]]

1. 1차원 배열 sort 전:  [ 8  2  4  5 10  1]
2. 1차원 배열 sort 후(오름차순):  [ 1  2  4  5  8 10]
3. 1차원 배열 sort 후(내림차순):  [10  8  5  4  2  1]

6. axis=None(flattened): [  1   2   4   5   8  10  33  66  67  77  90 100]

[[  8   2   4]
 [ 99  44  33]
 [100  67  77]]
[[  2   4   8]
 [ 33  67 100]
 [ 44  77  99]]


In [81]:
# 5. np.all, np.any ==> 논리값을 가진 다차원 배열을 하나의 논리값으로 처리할 때 사용
print("1. 모든 값이 True 냐?: ", np.all([True, True])) #  True
x = np.array([1,0,0,0])
print("2. np.all(arr): ", np.all(x)) #  False
print("3. np.any(arr): ", np.any(x)) #  True

# 6. np.all, np.any 활용
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(a>b)
print("all a>b ?:", np.all(a > b)) # False
print("any a>b ?:", np.any(a > b)) # False

1. 모든 값이 True 냐?:  True
2. np.all(arr):  False
3. np.any(arr):  True
[False False  True  True]
all a>b ?: False
any a>b ?: True


In [82]:
# 7. 전치  (Transpose)
arr = np.arange(15).reshape(3,5)
print("1. original: ", arr)
print()
print("2. T:", arr.T)  # Transpose
print("3. transpose()",arr.transpose())  # Transpose

# 8. 행렬곱( dot product(점곱), 곱해서 합 ) ==>  np.dot(a,b),  a @ b (중요)
'''
  벡터 내적: 1차원인 벡터간의 곱연산후 합 의미
  행렬곱(점곱, dot product): 행렬간의 곱연산후 합 의미
'''
arr = np.arange(4).reshape(2,2)
print("1. original: ",arr)
print("2. np.dot(arr, arr2) - 행렬곱:  ",  np.dot(arr,arr))
print("4. arr @ arr2) - 행렬곱:  ",  arr @ arr )
arr = np.arange(4)
print("5. 벡터 내적: ", np.dot(arr, arr)) # 0*0 + 1*1 + 2*2 + 3*3 = 14

1. original:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

2. T: [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
3. transpose() [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
1. original:  [[0 1]
 [2 3]]
2. np.dot(arr, arr2) - 행렬곱:   [[ 2  3]
 [ 6 11]]
4. arr @ arr2) - 행렬곱:   [[ 2  3]
 [ 6 11]]
5. 벡터 내적:  14


#### 차원 변경

In [90]:
# 차원 증가
# 1) reshape((행, 열))
arr1D = np.array([1, 2, 3])
print(arr1D, arr1D.shape)

arr2D = arr1D.reshape((1, -1)) # (1, 3)
print(arr2D, arr2D.shape)
print('-'*100)

# 2) np.expand_dims(arr1D, axis=0)
arr1D = np.array([1, 2, 3])
arr2D = np.expand_dims(arr1D, axis=0)
print(arr2D, arr2D.shape)
print('-'*100)

# 3) arr1D[np.newaxis, …(:)] -> 최근 많이 사용
arr1D = np.array([1, 2, 3])
arr2D = arr1D[np.newaxis, :]
print(arr2D, arr2D.shape)

[1 2 3] (3,)
[[1 2 3]] (1, 3)
----------------------------------------------------------------------------------------------------
[[1 2 3]] (1, 3)
----------------------------------------------------------------------------------------------------
[[1 2 3]] (1, 3)


In [106]:
# 차원 감소
# 1) np.squeeze(arr2D, axis=0): n차원 -> n-1차원
arr2D = np.arange(3).reshape(1, 3)
print(arr2D, arr2D.shape)
arr1D = np.squeeze(arr2D, axis=0)
print(arr1D, arr1D.shape)
print('-'*100)

# 2) arrND.flatten(): n차원 -> 1차원, 복사본 반환(원본 영향 X)
# 3) arrND.ravel(): n차원 -> 1차원, view 반환(원본 영향 O)
xxx = arr2D.flatten()   # 복사본 반환
yyy = arr2D.ravel()     # 원본과 연결

arr2D[0, 0] = 100
print(arr2D)
print("flatten:", xxx)
print('ravel:', yyy)

[[0 1 2]] (1, 3)
[0 1 2] (3,)
----------------------------------------------------------------------------------------------------
[[100   1   2]]
flatten: [0 1 2]
ravel: [100   1   2]


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
'''
[[1 2 3]
 [4 5 6]]
'''
print("색인1:", arr[..., 0])
print("색인2:", arr[..., [0]])

xxx = np.insert(arr, 0,  [[100],[200]], axis=1)
print(xxx)
'''
[[100 200   1   2   3]
 [100 200   4   5   6]]
'''
xxx = np.insert(arr, [0], [[100],[200]], axis=1)
print(xxx)
'''
[[100   1   2   3]
 [200   4   5   6]]
'''

색인1: [1 4]
색인2: [[1]
 [4]]
[[100 200   1   2   3]
 [100 200   4   5   6]]
[[100   1   2   3]
 [200   4   5   6]]


'\n[[100   1   2   3]\n [200   4   5   6]]\n'