## 6/9(금)

### numpy 작동 확인
- uninstall 방법 `pip uninstall numpy`

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


### 1차원 배열

#### 1. 1차원 배열 생성

In [3]:
# 배열 생성: np.array() 사용

list_value = [10,20,30]  # list, tuple, set , 정수의 기본 dtype은  int32 ( 4byte )
vector1 = np.array(list_value)
print(list_value, type(list_value))
print(vector1, type(vector1), vector1.dtype)

[10, 20, 30] <class 'list'>
[10 20 30] <class 'numpy.ndarray'> int32


In [4]:
list_value = [10.,20.,30.]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [5]:
# upcasting: 자동으로 큰 데이터 타입으로 변경되는 것
list_value = [10.,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

[10. 20. 30.] <class 'numpy.ndarray'> float64


In [8]:
# 명시적으로 데이터 타입을 변경 가능
list_value = [10.,20.,30.]
vector1 = np.array(list_value, dtype=np.int32)
print(vector1, type(vector1), vector1.dtype)

[10 20 30] <class 'numpy.ndarray'> int32


#### 2. ndarray의 속성

In [10]:
list_value = [10,20,30]
vector1 = np.array(list_value)
print(vector1, type(vector1), vector1.dtype)

# print(dir(vector1))

# 'T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 
# 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 
# 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 
# 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 
# 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 
# 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 
# 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view'

[10 20 30] <class 'numpy.ndarray'> int32


In [11]:
print("1. 벡터의 차원(dimension,axis)갯수:", vector1.ndim)
print("2. 벡터의 각 차원의 크기(shape):", vector1.shape) # tuple로 반환된다.
print("3. 벡터의 총 요소 갯수(size):", vector1.size)
print("4. 벡터의 저장 데이터 type(dtype):", vector1.dtype)

1. 벡터의 차원(dimension,axis)갯수: 1
2. 벡터의 각 차원의 크기(shape): (3,)
3. 벡터의 총 요소 갯수(size): 3
4. 벡터의 저장 데이터 type(dtype): int32


#### 3. 랜덤함수로 벡터 생성

In [16]:
# 1) 랜덤값 고정
np.random.seed(1234)

# 2) np.random.random([갯수])
# 0.0 <= 값 < 1.0 사이의 임의의 float 5개 랜덤값 반환. 갯수 생략하면  1개반환
print("1. random(5)")
arr = np.random.random()
arr = np.random.random(5)
print(arr, type(arr), arr.dtype)

1. random(5)
[0.62210877 0.43772774 0.78535858 0.77997581 0.27259261] <class 'numpy.ndarray'> float64


In [19]:
# 3) np.random.rand([갯수])
# 0 ~ 1의 균등분포에서 표본 추출. 갯수 생략하면  1개반환
print("2. rand(5)")
arr = np.random.rand()
arr = np.random.rand(5)
print(arr, type(arr), arr.dtype)

2. rand(5)
[0.37025075 0.56119619 0.50308317 0.01376845 0.77282662] <class 'numpy.ndarray'> float64


In [22]:
# 3) np.random.randn([갯수])
# 표준편차가 1이고 평균값이 0인 정규분포에서 표본 추출. 갯수 생략하면  1개반환
print("3. randn(5)")
arr = np.random.randn()
arr = np.random.randn(5)
print(arr)

3. randn(5)
[-0.28694235  0.44143825 -0.76987271 -0.97456841  0.70900741]


In [28]:
# 4) np.random.randint(low, high, n)
# 주어진 최소/최대 범위 안에서 임의의 난수 n개 추출
print("4. randint(1,10,3)")
arr = np.random.randint(1,10,3)
print(arr)

4. randint(1,10,3)
[5 3 8]


In [31]:
# 4) np.random.randint(high, size=n)
# 0 ~ 최대(exclusive) 범위안에서 임의의 정수 n개 반환, 복원추출
print("4. randint(5, size=4): ")
arr = np.random.randint(5, size=4)
print(arr)

4. randint(5, size=4): 
[2 1 2 1]


In [34]:
# 5) np.random.choice(리스트)
# 주어진 리스트에서 임의의 값 1개 반환
print("5. np.random.choice(['foo','bar','baz'])")
choice_value = np.random.choice(['foo','bar','baz'])
print(choice_value)

5. np.random.choice(['foo','bar','baz'])
bar


In [35]:
# 6) np.random.shuffle(리스트)
# 주어진 리스트를 shuffle 함.  in-place(True)로 동작됨.
print("6. np.random.shuffle(1,3,56,7,98])")
shuffle_value = [1,3,56,7,98]
np.random.shuffle(shuffle_value)
print(shuffle_value)

6. np.random.shuffle(1,3,56,7,98])
[56, 1, 3, 7, 98]


#### 4. 특정 값으로 벡터를 생성

In [37]:
# 1. np.zeros(shape)
# shape만큼 0으로 채움. 기본 type은 float64
print("1. np.zeros(5):")
data = np.zeros(5)
print(data, data.dtype)
data = np.zeros(5, dtype=np.int32)
print(data, data.dtype)

1. np.zeros(5):
[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [38]:
# 2. np.ones(shape)
# shape만큼  1.0 으로 채움. 기본 type은 float64
print("2. np.ones(5):")
data = np.ones(5)
print(data , data.dtype)
data = np.ones(5, dtype=np.int32)
print(data, data.dtype)

2. np.ones(5):
[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] int32


In [42]:
# 3. np.empty(shape)
# shape 만큼 임의의 값으로 채워짐 ==> 임의의 값으로 초기화 시킨 것
print("3. np.empty(3)")
data = np.empty(3)
print(data , data.dtype)
data = np.empty(3, dtype=np.int32)
print(data , data.dtype)

3. np.empty(3)
[10. 20. 30.] float64
[5 3 8] int32


In [43]:
# 4. np.full(shape, 값)
# shape 만큼 지정된 값으로 채워짐
print("4. full(5, 10)")
data = np.full(5, 10)
print(data)

4. full(5, 10)
[10 10 10 10 10]


#### 5. np.arange

In [46]:
print("1. arange(10)")
data = np.arange(10)  # [0,10) 형식으로 표현
print(data)

print("2. arange(1,11)")
data = np.arange(1,11) # [1,11)형식으로 표현
print(data)

print("3. arange(1,11,2)")
data = np.arange(1,11,2) # start, end(exclusive), step
print(data)

1. arange(10)
[0 1 2 3 4 5 6 7 8 9]
2. arange(1,11)
[ 1  2  3  4  5  6  7  8  9 10]
3. arange(1,11,2)
[1 3 5 7 9]


In [47]:
# float값으로 설정하기
print("4. float으로 설정1")
data = np.arange(5, dtype=np.float32)
print(data) # [0. 1. 2. 3. 4.]

print("4. float으로 설정2")
# float값 지정하면 float 값 반환됨.
data = np.arange(5.0)
print(data) # [0. 1. 2. 3. 4.]

4. float으로 설정1
[0. 1. 2. 3. 4.]
4. float으로 설정2
[0. 1. 2. 3. 4.]


#### 6. np.linspace
- np.linspace(start, stop, [num=50, endpoint=True])
- 기본적으로 stop값이 범위에 포함되고, 포함시키지 않으려면 endpoint=Flase로 지정한다.

In [50]:
print("1. np.linspace(0, 1, 11)")
# 0 <= 값 <= 1 사이의 값을 11개 생성
data = np.linspace(0, 1, 11 )
print(data, data.dtype)

print("2. np.linspace(0, 0.9, 10)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10)
print(data)

print("3. np.linspace(0, 0.9, 10, endpoint=False)")
# 0 <= 값 <= 0.9 사이의 값을 10개 생성
data = np.linspace(0, 0.9, 10, endpoint=False)
print(data)

1. np.linspace(0, 1, 11)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] float64
2. np.linspace(0, 0.9, 10)
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
3. np.linspace(0, 0.9, 10, endpoint=False)
[0.   0.09 0.18 0.27 0.36 0.45 0.54 0.63 0.72 0.81]


#### 7. 1차원 배열 삭제
arr = np.delete(arr, idx|fancy|slice, axis )

      - 삭제된 새로운 배열을 반환(in-place false, 원본이 유지된다.)
      - 순방향, 역방향 모두 가능
      - axis=None 이면 flatten 적용됨. => 다차원이 1차원으로 변경
      - slice인 경우에는  np.s_[::2]  형식 사용한다.

In [55]:
# 1. idx|fancy|slice 삭제
print("1. idx로 삭제")
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr,0)
print(new_arr)
new_arr = np.delete(arr,1)
print(new_arr)
new_arr = np.delete(arr,-1)
print(new_arr)

print("2. fancy 삭제") #  [idx, idx2, idx3] 여러 idx를 지정하는 방식. numpy에만 지원
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, [0,3,5] ) # fancy 인덱싱(정수배열 인덱싱)
print(new_arr)
new_arr = np.delete(arr, [0,3,5,-2] )
print(new_arr)

print("3. slice 삭제,  np.s_[::2]") # 대괄호만 쓰면 error 발생
arr = np.array([9,8,7,5,4,3])
print(arr)
new_arr = np.delete(arr, np.s_[0:4] ) # slice 삭제
print(new_arr)

1. idx로 삭제
[9 8 7 5 4 3]
[8 7 5 4 3]
[9 7 5 4 3]
[9 8 7 5 4]
2. fancy 삭제
[9 8 7 5 4 3]
[8 7 4]
[8 7]
3. slice 삭제,  np.s_[::2]
[9 8 7 5 4 3]
[4 3]
